cmd/kore-apiserver/server.go
- ensure you trim the .well-known/openid-configuration from the discovery url
=> Discovery URL

pkg/controllers/management/namespaceclaims/controller.go, pkg/controllers/management/namespaceclaims/reconcile.go
- fixing up the namespace claim to take into account the cluster status
- watching the kubernetes clusters as a means to retrigger the reconcilation
When the cluster is pending the namespace claim will not error it will just show pending
fixes #104
=> Namespace Claim Fix

doc/quick-start.md
This is a rework of the quick start guide.
My aim was  to clarify how to setup Kore and that the end result is the provisioning of a team cluster.
Included are explanations of,
- Simplified expected requirements.
- GCP account setup.
- Minor content re-shuffle.
- Moving the animated GIF to a dedicated provisioning a team cluster section.
=> Quick start updates

.circleci/config.yml, Makefile
This should make managing the release version and what images are used for testing easy to control - for now.
=> Optional direct GIT release version as used for images

cmd/korectl/main.go, pkg/cmd/korectl/config.go, pkg/cmd/korectl/helper.go
Basic behaviours:
1. Running `korectl` without any arguments
It prints the help.
Exit code: 0 (default behaviour)
1. Running `korectl` with an unknown command, e.g. `korectl foo``
```
Error: unknown command "foo"
Please run `korectl help` to see all available commands.
```
Exit code: 1
1. Any usage errors, e.g. `korectl --foo`
```
Error: flag provided but not defined: -foo
```
Exit code: 1
The `CommandNotFound` handler wasn't called as the default action was defined.
This means the first parameter was considered as an argument instead of a command name.
=> Fix CLI behaviour for some basic use-cases

pkg/clusterappman/clusterappman.go
Fixes #181
Now waits long enough for all the CRD's etc to come good:
```
$ kubectl -n kore get cm kore-cluster-status -o yaml
apiVersion: v1
data:
components: |
- detail: We have to assume ok as we do not have an application to track
message: System component not checked
name: Application Controller
status: Success
- message: all components ready
name: Helm Chart Operator
status: Success
- message: all components ready
name: Kore Helm Repository
status: Success
kind: ConfigMap
metadata:
creationTimestamp: "2020-02-27T13:03:28Z"
name: kore-cluster-status
namespace: kore
resourceVersion: "360734"
selfLink: /api/v1/namespaces/kore/configmaps/kore-cluster-status
uid: 8bf91cd6-5961-11ea-b5f7-4201ac100006
```
=> more appropriate timeout in advance of issue #89

pkg/cmd/korectl/auth.go
- ensure we have a server endpoint in the current context
- cleaning up the messages a little
- reducing the time we are willing to wait from 60 -> 20 seconds (perhaps still too high)
=> Korectl Auth

pkg/clusterappman/manifests/captain/captain.yaml
Just a wrong label - other issues with application controller but this should fix our first issue.
=> fix invalid label for application kind

pkg/cmd/korectl/create.go, pkg/cmd/korectl/delete.go, pkg/cmd/korectl/get.go, pkg/cmd/korectl/requestor.go, pkg/cmd/korectl/resource.go, pkg/cmd/korectl/teams.go
* Add create team command (does not update an existing resource)
* Make the team commands work with singular and plural expressions
* Print custom columns for a team
* Make the requestor accept a runtime.Object instead of an unstructured one
* Allow to register a custom response handler in Requestor
* Add Exists method to requestor
* Handle 404 errors in parseResponse instead of makeRequest in requestor
=> Team cli commands

Makefile
- ensure the anonymous anonymous volumes go
The reason being is on demo people usually have volumes from an old demo laying around (namely mariadb)
=> Docker Volumes

pkg/cmd/korectl/clusters.go, pkg/cmd/korectl/create.go, pkg/cmd/korectl/edit.go, pkg/cmd/korectl/localconf.go, pkg/cmd/korectl/prompts.go, pkg/cmd/korectl/requestor.go, pkg/cmd/korectl/teams.go
Add command for editing a team with prompts.
```
➜  kore git:(team_cli_commands) go run cmd/korectl/main.go edit team a-team
✔ Description : Bodie, Doyle, Tiger, the Jewellery Man█
"a-team" was successfully saved
➜  kore git:(team_cli_commands) go run cmd/korectl/main.go get team a-team
Name                Description
a-team              Bodie, Doyle, Tiger, the Jewellery Man
```
* Make a prompt use a string pointer as a value, to avoid mistakes with getvalue (and easier to update struct fields)
* Remove Body() from requestor and remove json unmarshaling from makeRequest
* The RuntimeObject allows request reuse (get + update)
=> Add edit team command

Makefile, pkg/clusterappman/manifests.go
This fixes the release workflow on CircleCI for master builds.
Any reason we don't commit pkg/clusterappman/manifests_vfsdata.go in?
=>  Add generate-clusterappman-manifests as a dependency to kore-apiserver

pkg/cmd/korectl/localconf.go, pkg/utils/marshall.go, pkg/utils/marshall_test.go
The current implementation was encoding straight to yaml; this creates problems as the structs do not have yaml tags and so the encoder encodes directly (and incorrectly). This also adds the creation of the allocation of the credentials to the teams
```YAML
typemeta:
kind: GKECredentials
apiversion: gke.compute.kore.appvia.io/v1alpha1
objectmeta:
name: gke
generatename: ""
```
to
```YAML
apiVersion: config.kore.appvia.io/v1
kind: Allocation
metadata:
creationTimestamp: null
name: gke
namespace: kore-admin
spec:
name: gke
resource:
group: gke.compute.kore.appvia.io
kind: GKECredentials
```
=> Fix Local Manifest Generation

pkg/cmd/korectl/local.go, pkg/cmd/korectl/locallogs.go
This completes https://github.com/appvia/kore/issues/254
It adds a logging sub command for `korectl local`,
```
./korectl local logs --help
NAME:
korectl local logs - View logs from local Kore.
USAGE:
korectl local logs [command options] [arguments...]
OPTIONS:
--follow, -f  Follow log output.
```
=> CLI local logs

hack/compose/demo.yml
- bumping the version of the demo to v0.0.12 as we have changes to the api https://github.com/appvia/kore/commit/54a3b9bf0b1ccf616c3afd1e1c6c96c46d845952 which the korectl now uses
=> Bump Demo Version

cmd/kore-apiserver/options/options.go, cmd/kore-apiserver/server.go, pkg/cmd/korectl/create_cluster.go, pkg/controllers/cloud/gcp/gke/reconcile.go, pkg/controllers/management/kubernetes/reconcile.go, pkg/kore/types.go
The current implementation does not surface errors on the cloud provider on the CLI or UI, instead the cluster is left in a pending state. This PR (feature toggled) adds a check to the cluster to if backed by a provider is checks the status of the cloud provider and reflects any errors from downstream.
b5935f7 - adding the feature toggle for the controller to check the status of provider
93b5a57 - checking the status of the cloud provider of the cluster and surfacing any errors
acbf22a - updating the create_cluster error to display the full status
So when I add invalid credentials, where as before I stayed pending forever; we got the error: 
```shell
status:
components:
- detail: invalid character 'B' looking for beginning of value
message: Failed to create GKE client, please check …
```
=> Cloud Provider Check

pkg/cmd/korectl/prompts.go
Closes https://github.com/appvia/kore/issues/280
This caused a bug during `korectl login` ... Client Secret had extra space, which failed IDP authentication.
=> Prompts now trim space from gathered user input.

pkg/controllers/cloud/gcp/gkecredentials/reconcile.go
1. Always define a variable in the smallest required scope
2. The value of verified won't be thread safe
=> Move the verified variable to the local scope

pkg/apiserver/invitations.go, pkg/apiserver/teams.go, pkg/apiserver/types/types.go, pkg/kore/invitations.go
This will allow us to show a better message to the user and we can optionally take the user to the team page they have just been added to.
=> Return the team name in the invitation handler

Makefile, hack/bin/run-api-with-env.sh
api server gets built properly with versions which are used for pulling oicd-proxy and clusterappman images so `go run ...` will use `latest` and not the correct image.
@bandesz Small one as reviewed.
=> fix the image versions when testing

cmd/auth-proxy/main.go, cmd/kore-apiserver/main.go, cmd/kore-clusterappman/main.go, cmd/korectl/main.go, pkg/cmd/app.go, pkg/cmd/app_test.go, pkg/cmd/korectl/apply.go, pkg/cmd/korectl/audit.go, pkg/cmd/korectl/clusters.go, pkg/cmd/korectl/create.go, pkg/cmd/korectl/create_cluster.go, pkg/cmd/korectl/create_namespace.go, pkg/cmd/korectl/delete.go, pkg/cmd/korectl/edit.go, pkg/cmd/korectl/get.go, pkg/cmd/korectl/teams.go
The urfave/cli library uses the standard flags library which stops parsing flags when it finds the first non-flag argument.
We would like to be able to parse the `--team` argument anywhere, similar to how `kubectl` handles the `--namespace` flag. (But kubectl uses cobra)
This adds a CLI app wrapper which takes the CLI arguments and reorders them:
- any global flags will be moved to the beginning of the list (so the cli library will parse them as flags and not arguments)
The custom cli app wrapper registers a custom help printer which adds the global flags to all command help texts.
Because the global flags are now printed I removed the `--team` flag from all commands. We have to do this, because if you redefine the team flag on the command level, it breaks the cli lib and you can only …
=> Add cli app wrapper to parse global flags in any position and print global help

cmd/korectl/options/options.go, pkg/cmd/korectl/apply.go, pkg/cmd/korectl/clusters.go, pkg/cmd/korectl/create_cluster.go, pkg/cmd/korectl/create_namespace.go, pkg/cmd/korectl/default.go, pkg/cmd/korectl/delete.go, pkg/cmd/korectl/locallogs.go, pkg/cmd/korectl/login.go, pkg/cmd/korectl/teams.go
* Flag aliases are not supported in v2 anymore in the Name field (e.g. "user,u"), we have to use the Aliases field
* Removing some remaining command level team parameters
=> CLI v2 upgrade fixes

cmd/korectl/main.go, cmd/korectl/options/options.go, pkg/cmd/app.go, pkg/cmd/app_test.go, pkg/cmd/korectl/create_cluster.go, pkg/cmd/korectl/default.go
Based on the previous work this reorders the argument but takes into account the infomation provided from the commands themselves to order. On a side note, i'm sure will all agree - we need to move to another lib
- this fixes among things the positional arguments ... so commands like `korectl create clusters dev --plan gke-development -a gke -t devs` now work in any order.
Tested against all the commands so far
=> Command Line Arguments Reordering

doc/alpha-local-quick-start.md, pkg/cmd/korectl/clusters.go, pkg/cmd/korectl/helper.go, pkg/utils/file.go
Pretty simple one - when running on a machine where kubectl is installed but you've not yet used it, allows kubectl auth to work correctly. Tested and working locally.
=> Allow CLI to create kube config file if non-existant. Addresses #306.

pkg/apiserver/helpers.go, pkg/apiserver/teams.go, pkg/cmd/korectl/requestor.go, pkg/kore/clusters.go, pkg/kore/error_validation.go, pkg/kore/validation/err_validation.go
Adresses #292.
Introduces a structure for generalised validation error handling across the API whereby anything can throw a validation error in a way that will cause a structured validation error to be returned to callers of the API.
=> Validate cluster name is less than 40 chars when creating via API.

pkg/cmd/korectl/requestor.go, pkg/cmd/korectl/whoami.go
- fixing the rendering of the whoami command
The current implementation does not render the whoami command correctly. This is a bit of a hack as the jsonpath lib we using should probably hand us back the type rather than convert to a []byte{}.
```shell
Before:
[jest@starfury kore]$ korectl whoami
SLVE
Username                        Email                           Teams
rohith.jayawardene@appvia.io    rohith.jayawardene@appvia.io    [
kore-admin,
devs
After:
[jest@starfury kore]$ korectl whoami
Username                        Email                           Teams
rohith.jayawardene@appvia.io    rohith.jayawardene@appvia.io    kore-admin,devs
```
=> WhoAmI Command Rendering Fix

hack/update-codegen.sh, pkg/apis/clusters/v1/zz_generated.deepcopy.go, pkg/apis/org/v1/zz_generated.deepcopy.go
During the vendoring changes I broke `make deepcopy-gen` and it simply exits without errors.
I introduced the `--` parameter erroneously.
I've also included a couple of out-of-date generated files. ﻿
=> Fix deepcopy-gen

pkg/kore/helpers.go, pkg/kore/helpers_test.go, pkg/kore/teams.go, pkg/kore/types.go, pkg/kore/validation/err_validation.go
Teams are a little different in kore as they exist in both the database and k8s (for triggers). At the moment this leaves us open to the name being find in mysql but failing in k8s. This PR fixes the issue by ensuring the name complies with the k8s requirement (https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names). At the moment we only need to apply it here and k8s will handle the other resources for us.
=> Team Name Regex

.circleci/config.yml, Makefile, pkg/apis/config/v1/zz_generated_openapi.go, pkg/kore/helpers_test.go, pkg/register/assets.go
We easily forget to run `make apis`, so I've added a check to CircleCI which runs it and checks whether there are any changed files.
I've added a separate job for running the check-apis test and the swagger validation, so we can run this in parallel with the tests.
Additional changes:
* Updating outdated API resources
* Fix an unstable test
=> Check whether `make apis` was run

doc/alpha-local-quick-start.md, pkg/cmd/korectl/clusters.go, pkg/cmd/korectl/commands.go, pkg/cmd/korectl/create_cluster.go, pkg/cmd/korectl/kubeconfig.go, pkg/cmd/korectl/print.go
This resolves https://github.com/appvia/kore/issues/296.
We replace `korectl cli auth -t <a-team>` with `korectl kubeconfig -t <a-team>`.
The highlights,
- **Bug fix**: ensures only clusters with an Endpoint are added kubeconfig.
- Highlights `kubeconfig` modification results.
- Updates inline CLI documentation to include new `korectl kubeconfig...` command.
- Updates quick start to use new `korectl kubeconfig...` command.
- Decouples CLI code from actual action to aid any future CLI migration.
In action,
**Cluster, with endpoint available**
```shell script
bin/korectl kubeconfig -t team-appvia
```
**Cluster, with NO endpoint available**
```shell script
bin/korectl kubeconfig -t team-appvia
```
=> Replace `korectl cli auth`

pkg/cmd/korectl/helper.go, pkg/cmd/korectl/resource.go, pkg/utils/inflect.go
This handles exceptions like "kubernetes" and "eks/ekss" when loading the resource config.
I moved the inflect function to util, so we hide the library used and we can add any exception to one place.
=> Add kubernetes resource config, clean up custom path override logic

cmd/korectl/options/options.go, pkg/cmd/app.go, pkg/cmd/korectl/create_allocation.go, pkg/cmd/korectl/create_cluster.go, pkg/cmd/korectl/create_gcp_organization.go, pkg/cmd/korectl/create_gcp_projectclaim.go, pkg/cmd/korectl/create_member.go, pkg/cmd/korectl/create_namespace.go, pkg/cmd/korectl/create_secret.go, pkg/cmd/korectl/create_team.go, pkg/cmd/korectl/get.go, pkg/cmd/korectl/helper.go, pkg/cmd/korectl/requestor.go, pkg/cmd/korectl/resource.go, pkg/cmd/korectl/teams.go
At the moment the user (admin or developer) needs to know the name of the resource to retrieve it, which isn't the best user experience. Long term this needs to be in the API but for now we can auto generate them from the resourceConfigs. This is related to https://github.com/appvia/kore/issues/221 and the documentation for the CLI
Note PR https://github.com/appvia/kore/pull/386 should be merged first. The two extra commits on top of this are;
98392a8a Auto Generating the Resources
ebf425a2 - fixing the title for the resource
```shell
[jest@starfury kore]$ korectl get 
NAME:
korectl get - Retrieves one or more resources from the api
USAGE:
korectl get [command options] [TYPE] [NAME]
DESCRIPTION:
The object type accepts both singular and plural nouns (e.g. "user" and "users").
Examples: …
```
=> Auto Generated Resources 

cmd/korectl/options/options.go
- removing the unrequired (default: false), as v2 prints these now so was getting (default: false) BOOL (default: false)
=> Default Option Value

cmd/korectl/options/options.go
- adding non-blocking environment variable
`export NO_WAIT=true`
=> No Blocking Env

pkg/cmd/korectl/create_cluster.go, pkg/cmd/korectl/create_namespace.go, pkg/cmd/korectl/helper.go, pkg/controllers/management/namespaceclaims/reconcile.go, pkg/utils/unstructured.go
The wait on namespace claim was not working
a) the namespace claims are prefixed with the cluster so it needed to reflect
b) the unstructured type was not decoding due to missing Kind (this is an issue with the controller-runtime)
```
$ korectl create namespace -c dev -t devs <name>
```
It *should* return when complete and not pend until timeout
28b6adf8 - fixing up the resource name as namespaceclaims have the cluster prefix
ebe311ba - bypassing the missing kind on unstructured decoding
85ff39cb - removing the debug statement
=> Fix namespace claim wait

pkg/kore/authentication/types.go, pkg/kore/identity.go, pkg/kore/teams.go
fd8d44a4 - adding the IsMember method to the identity
4f6405e5 - changing the logic so only a admin or team member can delete the team
301a4649 - fixing up the comment
fixes #430
=> Allow team deletion

pkg/kore/clusters.go, pkg/store/client.go
- the controller runtime client appears to strip the gvk on get() but not list(). I recall seeing this as a known issue. Here we are using the registered schema to lookup the gvk again and fill in the detail if found
You can build a cluster and then push a namespace claim: `korectl create namespace -t <cluster_name>` .. Then use a curl to grab the resource direct
```shell
bash function
api ()  
{ 
curl -H "Content-Type: application/json" -H "Authorization: Bearer password" -s http://127.0.0.1:10080/api/v1alpha1${@}
}
api /teams/<name>/namespaceclaims/<ns_name>
- the apiVersion and kind should be missing ... 
- then run again off this branch and it should be part o of the payload
```
=> Controller Runtime Client GVK

pkg/kore/allocations.go
The allocation should pick up the team namespace if not set.
fixes issue https://github.com/appvia/kore/issues/417
=> Allocation Namespace Bug Fix

pkg/kore/gke.go, pkg/kore/helpers.go
At present the use via the CLI or API can delete the cloud provider before the cluster itself, which can lead to wierd outcomes. This PR ensures when the cloud resource is requested deletion we first check if it referenced anywhere and if so denies the deletion
- Create a cluster
- Try and delete the GKE resource `korectl delete gkes <name> -t <team>`. The deletion should be denied
=> Deleting GKE before Cluster Fix

pkg/controllers/cloud/gcp/gke/bootstrap.go, pkg/controllers/cloud/gcp/gke/reconcile.go, pkg/controllers/management/kubernetes/reconcile.go, pkg/controllers/register.go
7bfbbedc - fixing the gke bootstrap code as eks merge had removed the part where we create the credentials
8359aebd - removing the extra debug line
572d23a2 - ensuring a clean return
The merge of EKS has removed the section of code where GKE created it's k8s service token.
=> GKE Bootstrap Fix

ui/pages/teams/[name].js, ui/server/controllers/session.js, ui/server/routes.js
* amending to new command `kubeconfig` instead of `auth`
* showing CLI login command first
Fixes #443 
Fixed #444
=> Cluster access info fix

charts/kore/templates/secret.yaml
- the chart was not generating a know hmac, the kore-apiserver will gen a epherimal one which will effects the team invite urls
=> Kore Helm Chart - HMAC

pkg/apiclient/operations/operations_client.go, pkg/apiserver/apiserver_integration_test.go, pkg/apiserver/teams.go, ui/lib/components/cluster-build/ClusterOptionsForm.js, ui/lib/components/configure/GCPOrganizationsList.js, ui/lib/components/configure/GKECredentialsList.js, ui/lib/components/configure/Plan.js, ui/lib/components/configure/PlanList.js, ui/lib/components/configure/ResourceList.js, ui/lib/components/team/Credentials.js, ui/lib/components/team/GCPOrganization.js, ui/lib/components/team/PlanItem.js, ui/lib/utils/kore-api-client.js, ui/pages/configure/cloud.js
Exposing the plans we have to the admins under the GCP tab in Configure Cloud settings.
At this stage, it's only exposing what we currently have and not covering adding/editing.
Changing the look of the Configure Cloud page to have "vertical tabs" to separate sections.
=> View plans

pkg/cmd/korectl/login.go
This way your local firewall won't always ask whether you want to allow it
=> The http server used for the login callback should listen only on localhost

go.mod, go.sum, pkg/apis/config/v1/codec.go, pkg/cmd/korectl/create_secret.go, pkg/controllers/register/register.go, pkg/controllers/secrets/gcp/controller.go, pkg/controllers/secrets/gcp/doc.go, pkg/controllers/secrets/gcp/reconcile.go, pkg/kore/assets/secret_types.go, pkg/kore/secrets.go, pkg/utils/cloud/gcp/iam.go, pkg/utils/pointers.go, pkg/utils/retry.go, pkg/utils/retry_test.go, vendor/github.com/jpillora/backoff/LICENSE, vendor/github.com/jpillora/backoff/README.md, vendor/github.com/jpillora/backoff/backoff.go, vendor/github.com/jpillora/backoff/go.mod, vendor/modules.txt
ac080a58 - adding the vendors code
770c0021 - adding the retry logic and pointer utils
1664d44c - fixing up the base64 encoding of the secrets
c36cab12 - removing teh value from the error message
e046854e - adding the secret types to the kore assets (perhaps switch these to jsonschema at some point?)
bb6822c9 - adding the various cloud utils for gcp permissions
1491fa2d - adding the controller to verify the credentials for the gcp organization type
=> GCP Organization Credentials Verification

pkg/cmd/korectl/create.go, pkg/cmd/korectl/create_admin.go, pkg/cmd/korectl/create_member.go, pkg/cmd/korectl/delete.go, pkg/cmd/korectl/delete_admin.go, pkg/kore/members.go, test/e2e/integration/users.bats
- adds the ability to create and delete an administrator in kore (these are effectively shortcuts to -t kore-admin)
The only real change here is pulling the create member code out into a reusable method and adding to additional commands as aliases effective to add and delete from the kore-admin team.
```shell
$ korectl create admin -u <username>
$ korectl get member -t kore-admin
$ korectl delete admin -u <username>
$ korectl get member -t kore-admin
```
=> Create & Delete Admin

pkg/controllers/controllerstest/test.go, pkg/controllers/error.go, pkg/controllers/management/cluster/controller_test.go, pkg/controllers/management/cluster/delete.go, pkg/controllers/management/cluster/reconcile.go
I've returned a nil concrete value (*ReconcileError <nil>) in the reconciliation loop, which becomes a non-nil value when wrapped with the `error` interface.
From the Go docs: "an interface value that holds a nil concrete value is itself non-nil."
I've replaced the ReconcileError type with a simple CriticalError type and we only create it with a non-nil error.
=> Fix cluster controller non-nil errors

Makefile, doc/alpha-local-quick-start.md
Also update quickstart guide to reflect changes. Addresses #324 remaining open items.
To test without tagging a release:
1. Run make release-cli
2. cd ./cli-release/output
3. Unzip relevant zip file for your machine.
4. Follow steps in the updated alpha readme in this PR.
cc @ezodude to take a look at my updates to the alpha quickstart, @lewismarshall to check he's happy with how we're bundling the compose files into the zip (by simply zipping them for now) and @gambol99 to check I've not missed any files from hack required for local (basically included the compose folder and the CA folder).
Tested on mac amd64, all working correctly for a korectl local environment.
=> Embed required files for korectl local into distribution zips

.golangci.yml, go.mod, pkg/cmd/kore/completion.go, pkg/cmd/kore/create/admin.go, pkg/cmd/kore/create/cluster.go, pkg/cmd/kore/create/member.go, pkg/cmd/kore/create/namespace.go, pkg/cmd/kore/create/secret.go, pkg/cmd/kore/create/user.go, pkg/cmd/kore/delete/delete_admin.go, pkg/cmd/kore/kore.go, pkg/cmd/utils/helper.go
The errcheck linter is a cheap way to catch some trivial bugs, so I think we should keep it.
=> Reenable errcheck linting

pkg/controllers/management/cluster/reconcile.go
- we introduced a regressive bug in https://github.com/appvia/kore/pull/527/files#diff-9ea9eead3dbf6972775d3b10acfdc388R197 as we are not deepcopying and thus overwriting the change
```shell
[jest@starfury kore]$ kore get cluster dev -o json | jq '.spec'^C
[jest@starfury kore]$ kore get cluster dev -o json | jq '.spec.configuration.authProxyAllowedIPs'
[
"0.0.0.0/0"
]
[jest@starfury kore]$ kore edit cluster dev
clusters.compute.kore.appvia.io/v1/dev no changes
[jest@starfury kore]$ kore get kubernetes dev -o json | jq '.spec.authProxyAllowedIPs'
[
"0.0.0.0/0"
]
[jest@starfury kore]$ kore edit cluster dev
clusters.compute.kore.appvia.io/v1/dev configured
[jest@starfury kore]$ kore get kubernetes dev -o json | jq '.spec.authProxyAllowedIPs'
[
"1.1.1.1/32"
]
```
PR …
=> Bug Cluster Controller

ui/__tests__/lib/components/forms/ClusterBuildForm.test.js, ui/assets/styles.less, ui/lib/components/cluster-build/CloudSelector.js, ui/lib/components/cluster-build/ClusterOptionsForm.js, ui/lib/components/cluster-build/MissingCredential.js, ui/lib/components/forms/ClusterBuildForm.js
* choose from a cloud provider at the top, rather then k8s service
* more usage of CSS classes to prevent lots of inline style
* renaming from providers to credentials (I think this makes more sense)
More refactoring of this page will happen when we add project creation
=> Minor changes to look and wording of create cluster page

pkg/controllers/cloud/gcp/gke/delete.go, pkg/controllers/cloud/gcp/gke/gke_client.go, pkg/controllers/cloud/gcp/gke/reconcile.go, pkg/utils/structs.go, pkg/utils/structs_test.go
The current implementation use's blocking delete, update and create call. This removes those blocks and uses the current state to dictate next move.
862013e9 GKE Reconcilation Loop
88452697 - fixing up the gke delete
Just need to build and delete an GKE cluster
=> GKE Reconciliation Loop

charts/kore/templates/portal.yml, ui/config.js, ui/server/controllers/session.js
* it should show the publicly accessible API URL
* adding this to the portal deployment in the helm chart so it can be used by the UI
=> Fixing cluster access guide in the UI

pkg/controllers/cloud/aws/eksvpc/delete.go
This needs to use the team name not the cluster name `GetCredentials(ctx context.Context, vpc *eksv1alpha1.EKSVPC, team string)`
```shell
{"error":"you do not have permissions to the eks credentials","file":"/go/src/github.com/appvia/kore/pkg/controllers/cloud/aws/eksvpc/delete.go:61","func":"github.com/appvia/kore/pkg/controllers/cloud/aws/eksvpc.(*eksvpcCtrl).Delete.func1","level":"error","msg":"trying to retrieve the credentials","name":"rohith","namespace":"devs","team":"rohith","time":"2020-04-16T17:38:31Z"}
```
=> Credentials Check

ui/config.js
This came to light when using Okta as an IDP.
When given an OpenID URL the openid-client will setup an Issuer.
If the URL contains `.well-known/openid-configuration` then it will load the config from that endpoint.
If, as in our case the URL set in the config did not contain `.well-known/openid-configuration`, it will load the config from one of `/.well-known/openid-configuration` or `/.well-known/oauth-authorization-server`, depending on which one responds first (no joke)
The latter endpoint, `/.well-known/oauth-authorization-server`, did not have the same config ie. it was missing the `jwks_uri`
This meant that it was pretty much down to luck as to whether the Issuer was setup with the `jwks_uri` or not.
The Issuer is configured once per restart which is why restarting appeared to fix …
=> Fixing the missing jwks_uri issue

pkg/apis/core/v1/status_types.go, pkg/controllers/management/cluster/controller_test.go, pkg/controllers/management/cluster/helper.go, pkg/controllers/management/cluster/reconcile.go
This is missing from the current reconcile loop.
The controller will monitor the component status and remove the component from the cluster's status if it was deleted.
=> Delete EKS NodeGroup from an existing cluster if it was removed from the configuration

hack/bin/run-api-with-env.sh
This will stop my Mac OS firewall popping up every time I start the server.
=> Run the kore-apiserver on localhost when you run it locally

cmd/auth-proxy/main.go
- the command.MarkFlagRequired() doesn't check the default value so fails
=> Auth Proxy Options

pkg/cmd/kore/assets/local_compose.go, pkg/cmd/kore/assets/local_support.go, pkg/cmd/kore/create/create.go, pkg/cmd/kore/create/ekscredential.go, pkg/cmd/kore/create/gkecredential.go, pkg/cmd/kore/delete/delete.go, pkg/cmd/kore/kore.go, pkg/cmd/kore/local/configure.go, pkg/cmd/kore/local/local.go, pkg/cmd/kore/local/logs.go, pkg/cmd/kore/local/start.go, pkg/cmd/kore/local/stop.go, pkg/cmd/kore/profiles/configure.go, pkg/cmd/utils/prompts.go, pkg/kore/ekscredentials.go
Also added gkecredentials and ekscredentials to kore CLI so we can do the full end-to-end flow without writing files containing credentials out to disk then applying them as per the previous local workflow.
To test:
1. unset VERSION and unset AUTHOR in the terminal, just in case, then run make kore.
2. bin/kore local configure
3. bin/kore local start
4. Use kore via CLI and via UI.
5. bin/kore local stop
Also included bugfix for eks credential deletion.
Addresses #598 and #547
=> Implement local command on kore CLI

.circleci/config.yml, hack/deploy-qa.sh
The current implementation is using latest when deploying to QA; it would be better to use sha1 and be certain of the version
=> Fix QA Images

pkg/kore/assets/plan_schema_eks.go, pkg/kore/assets/plan_schema_gke.go, ui/kore-api-swagger.json, ui/lib/components/ComponentStatusTree.js, ui/lib/components/cluster-build/ClusterOptionsForm.js, ui/lib/components/plans/PlanOption.js, ui/lib/components/plans/PlanOptionsForm.js, ui/lib/components/team/Cluster.js, ui/lib/kore-api/index.js, ui/lib/kore-api/kore-api-client.js, ui/lib/kore-api/model/V1alpha1EKSNodeGroupSpec.js, ui/package-lock.json, ui/package.json, ui/pages/audit/index.js, ui/pages/teams/[name]/audit.js, ui/pages/teams/[name]/clusters/[cluster].js, ui/server/controllers/swagger.js
Addresses #494 - Being able to drill-down into the detailed status of the cluster and it's sub-resources.
Addresses #493 - Being able to delete a cluster in a failed state.
Addresses #567 - Being able to edit an existing cluster's configuration after it is built through the UI.
Introduces the concept of 'immutable' plan parameters defined in the plan schema. These are parameters which cannot be edited after a cluster is created, such as region.
Drilling down into a sub-resource:
Editing cluster configuration:
=> Cluster visibility and editability through the UI.

pkg/cmd/utils/resource.go
Changes was made were the name in lookup is not automatically pluralized .. we need to use get GetAPIName() .. This fixes and get the suggestions for resources working again
- fixing up the autocompletion on the LookupResourceNames()
=> Get Resources Names for Autocompletion

ui/__tests__/unit/pages/teams/[name].test.js, ui/lib/kore-api/kore-api-client.js, ui/pages/_app.js, ui/pages/teams/[name].js
* available from a new dropdown menu on the team page
* this menu also includes access to the team audit
**New dropdown on team page**
**Clusters warning**
**Delete confirm**
=> Adding delete team functionality

pkg/kore/teams.go
The current implementation was only checking for Kubernetes which mean given we order it you could delete the team before all the resources (cloud provider) was removed
=> Team Deletion Bug

pkg/cmd/kore/profiles/configure.go, pkg/cmd/utils/prompts.go
Replace prompt in kore local configure to use manifoldco/promptui
Backspace didn't work when trying to edit the Kore API URL input:
```
Please enter the Kore API URL (e.g https://api.domain.com): asdfasdf^?^?^?^?
```
=> Replace prompt in kore local configure to use manifoldco/promptui

ui/lib/components/plans/PlanForm.js
* use the metadata name as the resource name if it exists
* create a resource name from the description if it's new
Fixes #657
=> Prevent duplicate plan being created after amending description

.circleci/config.yml, .gitignore, Makefile, doc/alpha-local-quick-start.md, ui/Makefile, ui/kore-api-swagger.json
Stop building korectl now we have kore as our supported CLI - Addresses #636
Create a packaged release of the helm chart with the appropriate tags - Addresses #624
Other minor changes:
- Align the UI and main makefiles for the swagger refresh so we stop getting pointless diffs.
- Update quickstart to reflect the CLI binary now being unzipped in the release.
- Publish releases **as a draft** from the pipeline - publishing the draft to a release is now a manual activity on github when we decide.
=> Stop building korectl and package helm chart

pkg/controllers/cloud/aws/eksvpc/delete.go, pkg/utils/cloud/aws/vpc_client.go
Currently we suffer from a number of issues when trying to delete the VPC. Though we are not the only ones
- https://github.com/weaveworks/eksctl/issues/1325
- https://github.com/aws/amazon-vpc-cni-k8s/issues/608
- https://github.com/terraform-providers/terraform-provider-aws/issues/11473
This issues appears to be related to the AWS CNI which isn't releasing the ENI. At present the only way to fix the bug is but manually deleting the ENI and the security group, removing the dep and allowing the VPC to delete. This PR trys to codify that fix, removing any flacky ENI and security groups. Note it doesn't remove everything attached to the VPC, so if they've attached additonal security groups not tagged as defined those will be left as blockers.
The terraform issue …
=> VPC Deletion

ui/__tests__/unit/lib/utils/validation.test.js, ui/lib/components/cluster-build/ClusterOptionsForm.js, ui/lib/components/forms/NamespaceClaimForm.js, ui/lib/utils/validation.js
* it should only allow alphanumerics and hyphen
* also moving the patterns and messages out to a validation file
* refactoring pattern validations to use this
This could be taken a lot further to include all field validations but it's a starting point.
Fixes #663
=> Fixing namespace name regex pattern

pkg/apiserver/helpers.go, pkg/apiserver/teams.go, pkg/store/client.go
There is a bug in the API server, that if you try to create certain resources for a non-existing team with a superadmin, it will return a 200 OK without any errors. This happens because:
- for superadmins we don't do team membership checks
- we don't check the team's existence in many of the team API endpoints
- we swallow an internal error when we update an object in Kubernetes
This change adds a filter to the Team API endpoints to always check the team's existence (except the team resource endpoints) + we don't swallow the internal error anymore.
=> Always check on the team API endpoints whether a team exists

cmd/kore-apiserver/options/options.go, cmd/kore-apiserver/server.go, pkg/client/config/config.go, pkg/client/config/types.go, pkg/cmd/errors/errors.go, pkg/cmd/kore/alpha/alpha.go, pkg/cmd/kore/apply/apply.go, pkg/cmd/kore/delete/delete.go, pkg/cmd/kore/featuregates/disable_feature_gate.go, pkg/cmd/kore/featuregates/enable_feature_gate.go, pkg/cmd/kore/featuregates/feature_gates.go, pkg/cmd/utils/factory.go, pkg/cmd/utils/handler.go, pkg/cmd/utils/helper.go, pkg/cmd/utils/resource.go, pkg/cmd/utils/resource_types.go, pkg/cmd/utils/types.go, pkg/kore/config.go, pkg/kore/feature_gates.go, pkg/kore/types.go
This is a prerequisite of https://github.com/appvia/kore/pull/652. You can decide whether you want to review the two stories separately or together.
This adds feature gates to the API server and the CLI. For now we have to set these separately, but in the future we should create an endpoint in the API, so the CLI and UI can query the enabled features.
The feature gates are stores in the Kore CLI's config as:
```
feature-gates:
services: false
```
The feature gates can be set on the API using the `--feature-gates="services=true"`, or using an env var: `export KORE_FEATURE_GATES="services=true"` 
By default services is disabled.
```
$ kore alpha feature-gates
FEATURE GATE    ENABLED
services        false
$ kore alpha feature-gates enable services
"services" feature gate was enabled
$ kore …
```
=> Add feature gates to the Kore API server and the CLI

ui/config.js, ui/pages/_app.js, ui/pages/prototype/configure/settings.js, ui/pages/prototype/index.js, ui/pages/prototype/setup/kore/cloud-access.js, ui/pages/prototype/setup/kore/complete.js, ui/pages/prototype/setup/kore/index.js, ui/server/index.js
Including adding a feature flag for showing prototypes
* prototypes can be added under `pages/prototype`
* this directory will only be served by next.js if `NODE_ENV` is `development` or specifically enabled by setting `KORE_UI_SHOW_PROTOTYPES` env var to true
* adding a tag/link to the header to show if the page being viewed is a prototype
* adding an index page to the prototype directory which can list and link to the prototypes as required
=> Adding prototypes for team settings and setup wizard

pkg/kore/assets/plan_policies.go, ui/__tests__/api-test-helpers.js, ui/__tests__/unit/lib/components/forms/EKSCredentialsForm.test.js, ui/__tests__/unit/lib/components/forms/GCPOrganizationsForm.test.js, ui/__tests__/unit/lib/components/forms/GKECredentialsForm.test.js, ui/__tests__/unit/lib/components/forms/VerifiedAllocatedResourceForm.test.js, ui/__tests__/unit/lib/components/policies/PolicyForm.test.js, ui/__tests__/unit/lib/utils/allocation-helpers.test.js, ui/lib/components/configure/ResourceList.js, ui/lib/components/forms/AllocationsFormItem.js, ui/lib/components/forms/EKSCredentialsForm.js, ui/lib/components/forms/GCPOrganizationForm.js, ui/lib/components/forms/GKECredentialsForm.js, ui/lib/components/forms/VerifiedAllocatedResourceForm.js, ui/lib/components/policies/Policy.js, ui/lib/components/policies/PolicyForm.js, ui/lib/components/policies/PolicyList.js, ui/lib/components/team/GKECredentials.js, ui/lib/kore-api/kore-api-client.js, ui/lib/utils/allocation-helpers.js, ui/pages/_app.js, ui/pages/configure/cloud.js
This PR introduces to the UI the ability to view, create, edit and delete plan policies through the UI, including allocating them to teams.
It is part of the work required for #536.
Additional changes in this PR:
- Allocations have been rationalised into a new, unit tested helper class to avoid repeating this logic in multiple places. This simplifies the allocation logic in a number of other parts of the UI (the various credentials forms) and will help when we include allocating plans, currently not possible through the UI.
- Minor tweak to the version number display (addresses #686).
=> UI Plan Policies - Create, Edit, View and Delete

ui/lib/prototype/components/configure/AutomatedProjectForm.js, ui/lib/prototype/components/credentials/GCPOrganization.js, ui/lib/prototype/components/credentials/GCPOrganizationForm.js, ui/lib/prototype/components/credentials/GCPOrganizationsList.js, ui/lib/prototype/components/forms/VerifiedAllocatedResourceForm.js, ui/pages/prototype/configure/settings.js, ui/pages/prototype/index.js, ui/pages/prototype/setup/kore/cloud-access.js
* setup wizard - don't show allocations on GCP organization credentials
* this required copying all the various GCP Organization components to the prototypes directories to make changes
* amending team settings inline with the setup wizard
=> [PROTOTYPE] Setup wizard and team settings changes

.circleci/config.yml, pkg/controllers/cloud/aws/eks/ensure.go, pkg/controllers/cloud/aws/eks/reconcile.go, pkg/controllers/cloud/aws/eksnodegroup/ensure.go, pkg/utils/cloud/aws/eks.go, pkg/utils/slices.go, pkg/utils/slices_test.go, test/e2e/check-suite.sh, test/e2e/integration/auth-proxy.bats, test/e2e/integration/eks.bats, test/trigger-e2e.sh
EKS Reconciliation Loop
Much like the change the eksnodegroup, this changed the reconcile loop to state based, no long running wait and uses re-queues to ensure exit
- removal of long waits
- added the eks update code to update the version and vpc settings
=> EKS Reconcilation Loop

.circleci/config.yml, Makefile
I think we were running the tests twice on CircleCI (without and with coverage).
Also I added a separate check job, which runs parallel to the tests (this way we can see linting errors quicker).
=> Separate check step on Circle CI, do not run tests twice

pkg/kore/assets/plans.go
The versions in our plans are not available anymore, so I bumped them to the latest.
`"1.15.11-gke.1` -> `1.15.11-gke.11`
=> Update GKE versions to latest

pkg/client/helper.go, pkg/cmd/kore/kore.go, pkg/cmd/utils/factory.go, pkg/cmd/utils/handler.go, pkg/cmd/utils/wait.go, pkg/utils/reflect.go
If you have a team set in your profile and your local token expired, `kore login` will throw an error saying `Authorization required` instead of logging you in.
This happened because we've always tried to check whether a team exists (if set in your profile).
Fix team existence checking in the Kore CLI:
* If there are authentication errors, ignore them in the check (this fixes e.g. kore login if the token is expired)
* Only do the team check when running a command which has a team parameter
=> Fix team existence checking in the Kore CLI

pkg/kore/setup.go
The current implementation overwrites the default plans everytime on boot, this PR adds a change to only update if the plan does not exist
=> Default Plans

pkg/cmd/kore/create/cluster.go, pkg/cmd/utils/wait.go
The current implementation forces you to select an allocation for the credential everytime. This PR performs a lookup to save the journey and defaults the use to a credential if only one is available for them
=> Default Cluster Allocation

cmd/auth-proxy/main.go, pkg/cmd/auth-proxy/filters/proxy/proxy.go, pkg/cmd/auth-proxy/server.go, pkg/cmd/auth-proxy/types.go
The current implementation has an issue when using kubectl log as the FlushInterval is not set in the reverse proxy and so isn't flushed correctly. We set a default here or 10ms (similar to another project) but allow it to be configurable on the command line
```Go
// FlushInterval specifies the flush interval
// to flush to the client while copying the
// response body.
// If zero, no periodic flushing is done.
// A negative value means to flush immediately
// after each write to the client.
// The FlushInterval is ignored when ReverseProxy
// recognizes a response as a streaming response;
// for such responses, writes are flushed to the client
// immediately.
FlushInterval time.Duration
```
=> Auth Proxy Streams

.circleci/config.yml
* build once using the commit sha or tag as the version
* docker tag that using the tag, or latest if there is no tag
* I think it makes sense that if you're running the latest image it will state the version as the commit sha or tag, rather than just latest
* this will also speed up the build as it doesn't build the docker image twice (layer caching doesn't seem to be very helpful here)
=> Prevent double docker build of UI

pkg/utils/render/format.go, vendor/k8s.io/apimachinery/pkg/util/duration/duration.go, vendor/modules.txt
The current implementation isn't very human friendly and was producing things like 520h40m20s. Switching to using the apimachinery formatting which rounds up the days and weeks
=> Age Format

pkg/controllers/management/namespaceclaims/delete.go
Allow a namespaceclaim to delete if the cluster is no longer there
=> [BUG] Namespace Bug

cmd/kore-clusterappman/server.go, pkg/clusterapp/clusterapp.go, pkg/clusterapp/helpers.go, pkg/clusterapp/types.go, pkg/clusterappman/clusterappman.go, pkg/clusterappman/helpers.go, pkg/clusterappman/helpers_test.go, pkg/clusterappman/types.go
Most notible updates include:
- runs the clusterapp deploys in a loop, (not just on startup)
- Adds status for the application kind itself
- Doesn’t crash with unkown types
=> Clusterapp updates

pkg/persistence/security.go, pkg/security/scanner.go
Tested locally, now shows clusters on the team security page as expected:
Addresses #817
=> Set owning team correctly when doing security scans

ui/assets/antd-var-overrides.less, ui/lib/components/plans/PlanForm.js, ui/lib/components/plans/PlanOption.js, ui/lib/components/plans/PlanOptionBase.js, ui/lib/components/plans/PlanOptionsForm.js, ui/lib/components/plans/custom/PlanOptionClusterUsers.js, ui/lib/components/plans/custom/index.js, ui/lib/components/services/ServicePlanForm.js
Allows hard-coded rich UI components for those fields that need them, while keeping the generic ones for the rest.
Includes a custom component for managing cluster users on both EKS and GKE.
Addresses #539 for the generic infra + cluster users, still need to do the EKS node groups control but that can be done as the next PR.
=> UI: Allow definition of custom form controls for named plan properties

ui/lib/components/plans/PlanForm.js, ui/lib/components/plans/PlanOption.js, ui/lib/components/plans/PlanOptionBase.js, ui/lib/components/plans/PlanOptionsForm.js, ui/lib/components/plans/custom/ConstrainedDropdown.js, ui/lib/components/plans/custom/KeyMap.js, ui/lib/components/plans/custom/PlanOptionClusterUsers.js, ui/lib/components/plans/custom/PlanOptionEKSNodeGroups.js, ui/lib/components/plans/custom/index.js, ui/pages/security/rules/[code].js
Allows editing and viewing of all node group properties.
Completes #539
From the plan, shows a list of node groups with basic high level details, and a button to add a new one:
Can delete a node group (will ask for confirmation, and only allows deletion when >1 exist, so you'll always have at least one).
Clicking the node group name / edit/view button brings up this drawer to specify all the details:
All values have been constrained where possible - at the moment the SSH security group and key values are still simply free text entry, will resolve those with a future PR as it would be good to constrain those to sensible values that exist, but that involves talking into the AWS API for the VPC in question.
Closes #539
=> UI: Implement custom control for EKS node groups.

ui/lib/components/setup/ExistingCloudAccounts.js, ui/lib/components/setup/GCPProjectAutomationSettings.js, ui/lib/components/setup/forms/RequestCredentialAccessForm.js, ui/pages/setup/kore/cloud-access.js
* toggle the request access email form and guidance based on a static property
* this can be ripped out when we've got the config endpoint to store/retrieve it from
* delete the AccountManagement allocation along with the resource
* prop-type not required fix for account managements
=> GCP project minor fixes

Makefile, charts/kore/templates/kore.yml, doc/install-kore-in-kind.md, hack/bin/run-api-with-kind.sh, images/Dockerfile.kore-apiserver.dev
This PR makes it possible to run the API server in Kind, while using your local Git repository and build the API server when the container starts.
The restart time is around 1 minute + while the API server initialises, which is not ideal, but still much quicker than having to build an image, push it and redeploy the Helm chart.
For now I only did this for the API server, as the UI doesn't have to run in Kind at all. If you need to run the API in Kind and you still want to develop the UI, you can run it locally on a different port for now.
=> Use Kind and Helm for development

pkg/apis/config/v1/plan_policy_types.go, pkg/apiserver/allocations.go, pkg/cmd/kore/create/ekscredential.go, pkg/cmd/kore/create/gkecredential.go, pkg/kore/allocations.go, pkg/kore/setup.go, test/e2e/integration/eks.bats, test/e2e/integration/gke-credentials.bats, test/e2e/integration/gke-deletion.bats, test/e2e/integration/gke.bats, test/e2e/integration/plan-policies.bats, test/e2e/integration/safeguards.bats, ui/__tests__/unit/lib/components/credentials/EKSCredentialsForm.test.js, ui/__tests__/unit/lib/components/credentials/GCPOrganizationsForm.test.js, ui/__tests__/unit/lib/components/credentials/GKECredentialsForm.test.js, ui/__tests__/unit/lib/components/policies/PolicyForm.test.js, ui/__tests__/unit/lib/utils/allocation-helpers.test.js, ui/lib/components/credentials/EKSCredentialsForm.js, ui/lib/components/credentials/GKECredentialsForm.js, ui/lib/components/resources/VerifiedAllocatedResourceForm.js, ui/lib/utils/allocation-helpers.js
* allocation resources will now be named using the resource kind (lowercase) as a prefix eg. gkecredentials-gke
* migrate old allocation name to new names on setup
* create allocations in the UI and CLI using the new name
* fixing UI bug where it was not showing the allocated teams correctly
* fixing the e2e tests
Note: the `PlanPolicy` allocations are created during setup, these will be created with the new names and momentarily the old ones will also be present until the renaming code is run. This will then check if an allocation with the new name exists before trying to create it. In this case, the allocation with the old name will be deleted. 
Fixes #679 
I tested this by creating all the different kind of allocations on the master branch, as follows:
```
dave@kore (master) $ k -n …
```
=> Fixing allocation naming clash

Makefile
The `check` Circle CI job is regularly killed. The default CPU limit is 12 for golangci-lint, so hopefully a more conservative one will solve this.
=> Limit golangci-lint to 2 cpus

scripts/kind_dev.sh
I forgot to add these two changes to a previous PR.
=> Fix kind deploy script: only create ns if doesn't exist, run helm upgrade with install

pkg/kore/setup.go
- fixing up the segmentation fault during an allocation migration
Trying to use the overwritten var at https://github.com/appvia/kore/pull/858/files#diff-cb9b42c972bf87145daaab12f65a6e6bR164
=> Fix Segmentation Fault

pkg/apiclient/models/v1_service_credentials_spec.go, pkg/apis/services/v1/service_credentials_types.go, pkg/apis/services/v1/zz_generated_openapi.go, pkg/apiserver/service_credentials.go, pkg/cmd/kore/get/get.go, pkg/cmd/kore/get/servicecredential.go, pkg/controllers/servicecredentials/delete.go, pkg/controllers/servicecredentials/ensure.go, pkg/kore/korefakes/fake_service_credentials.go, pkg/kore/service_credentials.go, pkg/register/assets.go, ui/kore-api-swagger.json, ui/lib/components/teams/service/ServiceCredential.js, ui/lib/components/teams/service/ServiceCredentialForm.js, ui/lib/kore-api/model/V1ServiceCredentialsSpec.js
This PR allows to set the secret name for service credentials, which is required if you want to have secrets with the same name in different namespaces.
I simplified the UI, so you only have to set the Secret Name when creating a secret and we automatically create the credentials object with the name: `[cluster name]-[namespace name]-[secret name]`.
=> Allow to specify secret name for a service credential

.circleci/config.yml
Set to tag if one is set, else go to SHA1. Current setup isn't picking up the tag on tagged releases.
=> Fix UI version tagging

test/e2e/integration/eks-deletion.bats
- we can't use the previous test as the services has introduced a timing error, we probably need to switch the check to use the component statuses instead
=> EKS E2E Deletion

ui/assets/styles.less, ui/lib/components/plans/UsePlanForm.js, ui/lib/components/services/ServiceOptionsForm.js, ui/lib/components/teams/cluster/Cluster.js, ui/lib/components/teams/cluster/ClusterAccessInfo.js, ui/lib/components/teams/cluster/ClusterBuildForm.js, ui/lib/components/teams/cluster/ClustersTab.js, ui/lib/components/teams/namespace/NamespaceClaim.js, ui/lib/components/teams/namespace/NamespaceClaimForm.js, ui/lib/components/teams/service/Service.js, ui/lib/components/teams/service/ServiceBuildForm.js, ui/lib/components/teams/service/ServiceCredential.js, ui/lib/components/teams/service/ServiceCredentialForm.js, ui/lib/components/teams/service/ServiceCredentialSnippet.js, ui/lib/components/teams/service/ServicesTab.js, ui/lib/components/utils/DataField.js, ui/lib/kore-api/kore-api-client.js, ui/lib/utils/ui-helpers.js, ui/pages/teams/[name]/clusters/[cluster].js, ui/pages/teams/[name]/services/[service].js
**Team page - clusters tab**
- namespaces are shown as a single line for each cluster, in a tag with the color showing the status of the namespace and tooltip with created date
- adding namespaces moved from here to cluster detail page
- show the cluster plan name that was used to create the cluster
**Team page - services tab**
- credentials are shown as a single line under each service, described as `cluster/namespace` in a tag with the color showing the status
**Cluster detail page**
- improved look, with larger header
- cluster access instructions added
- list and create namespaces from here
- improved form for creating service bindings
- service bindings are shown/created from under the relevant namespace
- bindings show `envFrom:` snippet for use in a k8s manifest
**Service detail …
=> Services UI improvements part 2

pkg/controllers/cloud/gcp/gke/bootstrap.go
Available since k8s 1.10 so backwards compatible with all versions of k8s we support.
Addresses #898
=> Use policy/v1beta1 instead of extensions/v1beta1 for Pod Security Policy

pkg/controllers/servicecredentials/ensure.go, pkg/controllers/servicecredentials/reconcile.go
Users can create services and service crendentials at the same time and we have to wait for an active service status until we can safely create credentials.
This fixes https://github.com/appvia/kore/issues/903
=> Wait for a an active service status when creating service credentials

.gitignore, Makefile, doc/install-kore-in-kind.md, images/Dockerfile.kore-apiserver.dev, scripts/kind_dev.sh, ui/Dockerfile.dev, ui/scripts/run-dev.sh, ui/scripts/run-prod.sh, ui/scripts/run-with-env.sh
* Build the kore-apiserver on the host, so it's much quicker
* Run the UI on the host as it's really slow in Kind and we show file sync issues
* Get the env vars for the UI from the relevant Kubernetes secrets
* ~When we build on Mac OS for Linux, there is a `core` file being created (core dump?). I have no clue why~ After upgrading to Go 1.13.12, the issue went away
=> Local development improvements

pkg/cmd/kore/kubeconfig/kubeconfig.go
- fixing up the bug where we'd retrieve the config for deleting cluster
- we can probably expand upon this and delete the context as well, but i'll leave that for another PR
=> Kubeconfig on deleting clusters

pkg/cmd/kore/get/servicecredential.go
You can't add an alias of zero length else you will get `kore get bash: aliashash[""]: bad array subscript` error
=> Kore Autocomplete Fix

pkg/kore/assets/plans.go, pkg/kore/setup.go, ui/lib/components/plans/PlanItem.js, ui/lib/components/plans/PlanList.js, ui/lib/kore-api/kore-api-client.js
Few small changes:
* Built-in plans are now read-only.
* Setup.go now overwrites the default plans on startup rather than only if they don't exist, so we can update our built-in plans easily.
* UI respects the read-only flag so doesn't present editing options for uneditable plans.
* UI can now delete plans (like the CLI always could).
=> Make default plans read-only, keep upgraded. Allow UI to delete plans.

test/e2e/integration/plans.bats
Checking release channel instead.
=> Fix E2E test - GKE plans no longer need exact GKE version

go.sum, pkg/controllers/services/reconcile.go, ui/lib/components/teams/cluster/ClustersTab.js, ui/lib/components/teams/cluster/applications/ClusterApplicationServiceForm.js, ui/lib/components/teams/service/Service.js, ui/lib/components/teams/service/ServiceBuildForm.js, ui/lib/components/teams/service/ServicesTab.js, ui/pages/teams/[name].js, ui/pages/teams/[name]/clusters/[cluster].js
* adding cluster application specific wrapper around the ServiceOptionsForm
* this adds the namespace selection and has different submission process
* new section on the cluster detail page
* Service component displays different for Cloud and Application services
**Cluster detail page**
**Team page clusters tab**
Fixes: #850
=> Adding cluster application services

hack/deploy-beta.sh, hack/deploy-qa.sh, ui/assets/styles.less, ui/lib/components/layout/SiderMenu.js, ui/lib/components/services/ServiceKindList.js, ui/lib/components/services/ServiceKindManage.js, ui/lib/components/teams/cluster/ClustersTab.js, ui/lib/utils/features.js, ui/pages/configure/cloud/[[...cloud]].js, ui/pages/configure/services/[kind].js, ui/pages/configure/services/index.js, ui/pages/teams/[name].js, ui/pages/teams/[name]/clusters/[cluster].js, ui/scripts/run-with-env.sh
* adding left-side menu button for "Services"
* both in-cluster and cloud services can be managed via this page
* filter the services on this page by platform and service name
* enabled/disabled now shown side-by-side
* some minor cosmetic changes to service admin in general
Closes #850
=> In-cluster services admin

.circleci/config.yml
We need visability of when changes can't be deployed.
=> notify when deploys fail

.circleci/config.yml, Makefile, hack/bin/http_test.sh, ui/Makefile, ui/scripts/install-e2e-deps.sh
This PR splits and parallelises a number of the circle CI steps to get the most expensive / lengthy steps underway as soon as possible.
It also uses the built binaries from the main 'build' step for e2e testing the UI, meaning the UI test step can be run on a node image instead of a golang one.
Lastly, it adds caching for node_modules to speed up the UI build time significantly.
=> Improve circleCI build times

ui/lib/components/credentials/EKSCredentials.js, ui/lib/components/credentials/EKSCredentialsList.js, ui/lib/components/credentials/GCPOrganization.js, ui/lib/components/credentials/GCPOrganizationsList.js, ui/lib/components/credentials/GKECredentials.js, ui/lib/components/credentials/GKECredentialsList.js, ui/lib/components/teams/AutoRefreshComponent.js, ui/lib/components/teams/cluster/Cluster.js, ui/lib/components/teams/cluster/ClustersTab.js, ui/lib/components/teams/namespace/NamespaceClaim.js, ui/lib/components/teams/namespace/NamespaceClaimForm.js, ui/lib/components/teams/namespace/NamespacesTab.js, ui/lib/components/teams/service/Service.js, ui/lib/components/teams/service/ServiceCredential.js, ui/lib/components/teams/service/ServicesTab.js, ui/lib/kore-api/kore-api-client.js, ui/pages/teams/[name]/clusters/[cluster]/services/[service].js
**Refactoring the AutoRefreshComponent class**
* refactoring parent classes and components they are used in
* no longer need to retain the item in the state once it's deleted
* removing the need to filter by not deleted everywhere
**Changing AutoRefreshComponent to use KoreApi**
* the relevant KoreApi function call is passed in as a prop to the component
=> Autorefresh improvements

ui/lib/components/credentials/EKSCredentials.js, ui/lib/components/credentials/GCPOrganization.js, ui/lib/components/credentials/GKECredentials.js, ui/lib/components/teams/AutoRefreshComponent.js, ui/lib/components/teams/cluster/Cluster.js, ui/lib/components/teams/cluster/ClustersTab.js, ui/lib/components/teams/namespace/NamespaceClaim.js, ui/lib/components/teams/service/Service.js, ui/lib/components/teams/service/ServiceCredential.js, ui/lib/components/teams/service/ServicesTab.js, ui/lib/prototype/components/credentials/GCPOrganization.js, ui/lib/prototype/components/teams/cluster/Cluster.js, ui/lib/prototype/components/teams/namespace/NamespaceClaim.js
* only do this if `stableRefreshMs` prop is defined
* renaming final states to stable states
* only trigger the final (now stable) state reached function if that status changed
* adding 60s stable refresh for clusters on the team page and services on the cluster page
=> Enhancing AutoRefreshComponent to refresh stable resources

pkg/controllers/management/kubernetes/aws_autoscaler.go, pkg/controllers/serviceproviders/reconcile.go, pkg/kore/service_plans.go, pkg/kore/service_providers.go, pkg/serviceproviders/application/application_suite_test.go, pkg/serviceproviders/application/factory.go, pkg/serviceproviders/application/plans.go, pkg/serviceproviders/application/plans_test.go
We've loaded the build-in app plans in the wrong place as:
- on a fresh install the app service kind won't exist at that point
- that code would run for all service providers, which we don't want
=> Bugfix: Move the built-in app service plans to the application providers

.circleci/config.yml, ui/__tests__/e2e/02-configure-cloud-gcp.test.js, ui/__tests__/e2e/03-configure-cloud-aws.test.js, ui/__tests__/e2e/config.js, ui/__tests__/e2e/page-objects/configure/cloud/cluster-policies-base.js, ui/__tests__/e2e/page-objects/configure/cloud/configure-cloud.js, ui/__tests__/e2e/page-objects/utils.js, ui/config.js, ui/config.public.js, ui/lib/components/layout/SiderMenu.js, ui/lib/components/policies/Policy.js, ui/lib/components/setup/GCPProjectAutomationSettings.js, ui/next.config.js, ui/pages/_app.js, ui/pages/configure/cloud/[...cloud].js, ui/pages/configure/cloud/index.js, ui/server/index.js
This makes tests much faster and less prone to random failures due to animations getting in the way. Should hopefully resolve the random failures we're seeing on a couple of the tests.
Also removed experimental feature from next.js and used the same approach as the teams page to show the default page correctly without the experimental catch-all slug being needed.
=> Disable animations for UI E2E tests

.circleci/config.yml, ui/Makefile, ui/lib/kore-api/model/V1alpha1EKSNodeGroupSpec.js
This introduces a check that the UI auto-gen is up to date at the point where circle CI has run up the API and pulled down the latest swagger.
It also fixes a missing auto-gen'd file that the check highlighted.
=> Check UI autogen

test/e2e/integration/eks.bats
- these need to be skipped for now as the services controller appears to have some issues
```shell
✓ We should have a default pod security policy eks.privileged
- We should see the number of nodes change when I update the desired state (skipped: autoscaling is enabled)
- If autoscaling is enabled in the cluster we should see the deployment (skipped: while the helm services controller is reviewed)
```
=> EKS Autoscaler Checks

ui/lib/components/teams/AutoRefreshComponent.js
* this issue was due to the addition of the stable refresh interval
* the resource calls to start refreshing when it's deleted which, when a stable refresh is taking place, created another interval which was never cleared
* the fix is to always clear the interval before setting a new one
=> Preventing multiple intervals being set when deleting a resource

pkg/controllers/helpers/services.go, pkg/controllers/management/kubernetes/aws_autoscaler.go
At the moment we use the plan name for the service that then manages the helm chart. This will not be unique when a second cluster is built for a team.
This PR addresses that.
=> change the name of the autoscaler service to be unique to a cluster

ui/lib/components/teams/cluster/ClusterOptionsForm.js
Bugfix for creating a cluster.
Resolves #975 
~- [ ] I've created a PR to update the [documentation](https://github.com/appvia/kore-docs): PR LINK~  _N/A_
Force render Collapse Panel to ensure the config is present. The issue was due to some data being read from the config when did not exist.
=> Force render Collapse Panel to ensure the config is present

.circleci/config.yml, CHANGELOG.md, pkg/apiserver/login.go
Resolves #999 
This has been tested by:
* Create new kore-in-kind configured to use Google as IDP
* Log in
* Push local time on laptop forward by 58 minutes
* Check still working (`bin/kore get teams --verbose` - note no token refresh)
* Wait until token expires (2 minutes)
* Check still working (`bin/kore get teams --verbose` - note token refresh being requested and access continuing to work)
Also regression tested against Auth0 by:
* Create new kore-in-kind with normal auth0 configuration.
* Repeat above test.
=> Request access type offline so we get a refresh token when the user logs in

.circleci/config.yml
Changes resources classes for certain CircleCI steps to avoid failures and improve end-to-end run time for critical path steps.
See https://app.circleci.com/pipelines/github/appvia/kore?branch=circle-resource-classes - 2 minute improvement in end-to-end run time and no failures from the 'test' job.
=> Increase resource class on various critical-path circle CI steps

CHANGELOG.md, pkg/apiserver/login.go, pkg/cmd/utils/factory.go
GSuite auth only returns a refresh token on the first ever login by a user to a project, unless the additional parameter 'approval_prompt=force' is added to the initial request. This PR adds such to authentication when the auth is configured to use `https://accounts.google.com`.
Resolves #1006 
~~- [ ] I've created a PR to update the [documentation](https://github.com/appvia/kore-docs): PR LINK~~ n/a
No changes to system behaviour. Refresh tokens now work for GSuite authentication as per other IDPs.
Remove offline_access from the scopes if configured (or left at default) and google authentication in use, as we know that will cause a failure.
Addtional debug and warning logging on CLI when refreshing / failing to refresh token, rather than silently …
=> Force approval when logging in to fix GSuite auth

test/e2e/integration/safeguards.bats
We've changed the error message when checking the object dependencies before deleting.
This only fixes the failing GKE E2E tests, the EKS errors are probably related to https://github.com/appvia/kore/issues/974
=> Update expected error message in E2E tests when trying to delete a team

ui/lib/components/credentials/GKECredentialsForm.js
Amending GKE credential to ask for Project ID, not name. This accurately reflects the data required.
Resolves #1009 
Please provide detailed instructions about how to test this feature. This should include:
* creating a new GKE credential
* editing GKE credentials
=> Amending GKE credential to ask for Project ID, not name

ui/__tests__/e2e/01-first-time-setup.test.js, ui/__tests__/e2e/02-configure-cloud-gcp.test.js, ui/__tests__/e2e/page-objects/configure/cloud/GCP/organizations.js, ui/__tests__/e2e/page-objects/configure/cloud/GCP/projects.js, ui/__tests__/e2e/page-objects/configure/cloud/configure-cloud.js, ui/__tests__/e2e/page-objects/setup-kore-cloud-access.js, ui/__tests__/unit/lib/components/plans/ManageClusterPlanForm.test.js, ui/__tests__/unit/lib/components/policies/PolicyForm.test.js, ui/__tests__/unit/lib/components/teams/members/MembersTab.test.js, ui/__tests__/unit/lib/kore-api/kore-api-resources.test.js, ui/__tests__/unit/lib/utils/validation.test.js, ui/__tests__/unit/pages/_app.test.js, ui/__tests__/unit/pages/teams/[name]/[tab].test.js, ui/lib/components/credentials/GCPOrganization.js, ui/lib/components/credentials/GCPOrganizationForm.js, ui/lib/components/credentials/GCPOrganizationsList.js, ui/lib/components/credentials/GKECredentials.js, ui/lib/kore-api/kore-api-client.js, ui/server/controllers/apiproxy.js
Be able to replace the service account JSON key for the configured GCP organization.
Be able to delete the configured GCP organization
Resolves #1011 
~- [ ] I've created a PR to update the [documentation](https://github.com/appvia/kore-docs): PR LINK~ _N/A_
Introducing a checkbox for replacing the Organization's JSON service account key.
Also adding functionality to delete the configured GCP Organization, this will also delete the associated `AccountManagement` CRD
Adding/enhancing E2E tests for GCP Organizations.
Please provide detailed instructions about how to test this feature. This should include:
* adding/editing GCP org
* deleting GCP org
* replacing service account JSON on GCP org
=> GCP Organization enhancements

CHANGELOG.md, ui/lib/components/teams/namespace/NamespacesTab.js
Fixing namespaces not appearing on the cluster page
Resolves #1016 
* a feature gate check was missing which broke the data fetching for the component
* meaning the namespace data was not fetched and therefore not shown
* this fix ensures we only request the service kind data when the services feature gate is enabled
Please provide detailed instructions about how to test this feature. This should include:
* creating a namespace and checking it appears after navigating away and coming back to the cluster page
I've tested creating a namespace with feature gates disabled, namespace was not showing. Once I applied this fix and reloaded the page, the namespace appeared as expected.
=> Fixing namespaces not appearing on the cluster page

ui/lib/components/teams/TeamHeader.js, ui/lib/components/teams/TeamSettings.js, ui/lib/components/utils/TextWithCount.js, ui/pages/teams/[name]/[tab].js, ui/pages/teams/[name]/audit.js, ui/pages/teams/[name]/clusters/[cluster]/[tab].js, ui/pages/teams/[name]/clusters/[cluster]/services/[service].js, ui/pages/teams/[name]/clusters/new.js, ui/server/controllers/apiproxy.js
Adding a team header for all team scopes pages
* this was previously only shown on the main team page
* this includes the cluster page, new cluster page, service page and team audit page
Resolves #586 
~- [ ] I've created a PR to update the [documentation](https://github.com/appvia/kore-docs): PR LINK~ _NA_
Please detail any major changes and provide the minimal documentation about how these work or do alter the current behaviour.
Anyone who reads this should understand the intention of this PR without reading the code.
* adding a utils component for tab titles, or more generally titles with badges showing a count
* removing unnecessary div elements in favour or react fragments on the team scoped pages
* fixing bug with apiproxy not returning response …
=> Team context header

scripts/kind_dev.sh
make kind-dev depended on only having a single clone of the kore code in the normal location in gopath. I use multiple clones of the kore code so i can switch easily between reviewing and ongoing work and quick fixes. This change allows that to work.
Run make kind-dev
=> Make kind-dev work even if you use a non-default path for the code.

ui/pages/configure/users.js
This is a trivial bugfix for the /configure/users page.
If you navigate to the /configure/users page, you'll get a 500 error page, which is a 401 Unauthorized under the hood - caused by a missing passed request context.
=> Bugfix: pass request context to kore client, otherwise /configure/users throws an error

pkg/clusterproviders/gke/schema.go, pkg/controllers/cloud/gcp/gke/gke_client.go, pkg/kore/clusters.go
The labels from the plan were not being applied to the actual configuration of the nodepool
Resolves #1035 
Just passing the label into the nodepool configuration. Note these are immutable and already tagged as so in the schema so no changed required for updates.
None
Build a cluster with a nodepool with labels
Should probably add to the E2E
=> GKE NodePool Labels

go.mod, pkg/cmd/kore/local/helm.go, pkg/cmd/kore/local/helper.go, pkg/cmd/kore/local/up.go, pkg/cmd/utils/handler.go
Fixing up the flag to do what is expected i.e. set the release version to what i selected. At the moment this is only used when no values.yaml exist
Resolves https://github.com/appvia/kore/issues/1033
When the `kore alpha local up --version <version>` is used the value is never ignored. 
I'v added an optional FlagsChanged which is actioned in the DefaultHandler; if the field exists a list of flags changed i.e. user defined flags are included. This allows you to know if the value is the default value or an actual value set on the command line.
`kore alpha local up`
`kore alpha local up --version <version>`
Just run with a `--version` with and without i.e perhaps latest or v0.2.4 and you ca verify the changes are done in the `~/.kore/values.yaml`
=> Kore Up Release Flag

.circleci/config.yml, go.mod, go.sum, vendor/modules.txt
We already used Go 1.14 in all our CircleCI builds and in our Docker images, so this PR updates the last 1.13 version reference.
I also did clean up go.mod a little and removed all "-mod=vendor" options, as 1.14 automatically detects this.
Some go.mod and vendor changes are the result of running `go mod tidy && go mod vendor`.
I removed all version pinnings from go.mod which wasn't used anymore (operator framework, thrift and prometheus bits)
I'll leave the `-mod=vendor` in the Makefile just in case, but maybe we should introduce a Go version check and force version >= 1.14
=> Use Go.14 in go.mod + cleanup

ui/__mocks__/requestInterceptorMock.js, ui/jest.config.js, ui/lib/kore-api/index.js, ui/lib/kore-api/request-interceptor.js
Throw a meaningful error if the `ctx` is missing from the KoreApi client for a server-side call.
=> Throw error if ctx is missing from server-side KoreApi client

.circleci/config.yml
CircleCI config update
Ensure E2E tests are done on alpha and beta tags as well as RC and finals.
=> Do E2E tests for alpha and beta tags as well as RCs and finals

pkg/persistence/configs.go, ui/lib/components/setup/CloudAccountAutomationSettings.js, ui/lib/components/setup/ExistingCloudAccounts.js, ui/lib/components/setup/forms/RequestCredentialAccessForm.js, ui/lib/components/teams/cluster/MissingCredential.js, ui/lib/kore-api/kore-api-client.js, ui/lib/kore-api/kore-api-resources.js, ui/lib/utils/validation.js
Configure and display email for requesting cloud account credentials
Resolves #1052 
~- [ ] I've created a PR to update the [documentation](https://github.com/appvia/kore-docs): PR LINK~ _NA_
* this is used when admins want to manage cloud accounts outside of Kore
* admins can set an email address which will be displayed to teams who do not have a credential allocated
* separate email addresses can be set for each cloud, GCP and AWS at this stage
* teams are shown this email address when they try to request a new cluster and do not have any allocated credentials
* adding email address during setup
* adding from configure/cloud pages
* viewing the email when creating new clusters with no …
=> Kore contact for teams to request cloud account credentials

ui/lib/components/plans/PlanViewer.js, ui/lib/components/setup/CloudAccountAutomationSettings.js
Fix for saving of account automation settings
Resolves #1070 
~- [ ] I've created a PR to update the [documentation](https://github.com/appvia/kore-docs): PR LINK~ _NA_
* adding a couple of checks when saving an `AccountManagement` CRD
- remove any rules which have no plans
- removing any rule plans which no longer exist
* set the filtered rules back to the state once saving
As per the bug detailed in #1070
=> Fix for saving of account automation settings

pkg/client/client.go, pkg/client/config/config.go, pkg/client/config/config_test.go, pkg/client/fake/client.go, pkg/client/types.go, pkg/cmd/kore/kore.go, pkg/cmd/kore/kubeconfig/kubeconfig.go, pkg/cmd/kore/login/login.go, pkg/cmd/kore/profiles/list.go, pkg/cmd/kore/profiles/show.go, pkg/cmd/utils/factory.go, pkg/cmd/utils/handler.go, pkg/cmd/utils/types.go
Adding the ability to explicitly set the profile on the current line.
**Which issue(s) this PR resolves**: 
Resolves #1095 
Nothing major has changed, we've simply added the ability in the client to override the current profile 
NA
NA
`kore --profile kore-qa get teams`
`kore --profile kore-demo login`
You should never switch to the `--profile <name>` profile - just use it for those requests
See above
NA
=> Kore CLI Profile Context Flag

ui/lib/components/plans/custom/PlanOptionClusterUsers.js
Incorrect property being used to determine enum of roles when editing cluster users.
Resolves #1101 
The following testing **has been performed**:
* Edit an existing cluster with no cluster users specified:
* Adding user with role works correctly.
* Edit an existing cluster with cluster users specified:
* Web page doesn't explode.
* Adding/editing users and roles works correctly.
=> Correct enum for clusteruser roles

.circleci/config.yml, examples/aks-credentials.yml, pkg/apis/aks/v1alpha1/akscredentials_types.go, pkg/controllers/cloud/azure/akscredentials/controller.go, pkg/controllers/cloud/azure/akscredentials/reconcile.go, pkg/controllers/components.go, pkg/controllers/register/register.go, pkg/utils/kubernetes/types.go, test/e2e/README.md, test/e2e/check-suite-units.sh, test/e2e/check-suite.sh, test/e2e/integration/aks-credentials.bats, test/e2e/integration/aks-deletion.bats, test/e2e/integration/aks.bats, test/e2e/integration/plan-policies.bats, test/e2e/plan-policies.bats, test/trigger-e2e.sh
This PR adds E2E tests for AKS.
Resolves #1083 
* A small amendment to the reconciler components, that objects are not required to have component statuses (see AKSCredentials as an example).
* I forgot to add a controller for the AKS credentials, so I've added a no-op for now. There is an other issue for implementing the proper creds verification: https://github.com/appvia/kore/issues/1089
```
CIRCLECI_TOKEN="..." test/trigger-e2e.sh --enable-aks true
```
* Verify credentials: https://github.com/appvia/kore/issues/1089
=> Add E2E tests for AKS, add controller for AKS credentials

.circleci/trigger.sh, pkg/persistence/store_test.go
Blindly retry as a tactical workaround for the SQL test failures we're getting on CircleCI. Sticking plaster until we work out a proper fix...
Work around for #1110
=> Blindly retry on test panic to workaround circleCI issue

pkg/cmd/kore/local/providers/kind/kind.go
Bumping the version of kubernetes to 1.16 for the kore up command
Resolves https://github.com/appvia/kore/issues/1106
Bumped the version of kind in kore alpha local up to 1.16.9.
`kore alpha local up`
=> Bump Kore Alpha Local Kind => 1.16.9

ui/__tests__/unit/lib/components/plans/ManageClusterPlanForm.test.js, ui/lib/components/plans/ManageClusterPlanForm.js, ui/lib/components/resources/ResourceList.js, ui/lib/components/setup/CloudAccountAutomationSettings.js, ui/lib/utils/cloud.js
Fixing bug when associating a new plan with account automation
Fixing issue when saving account management from plan form
Resolves #1071 
Fixing bug when associating a new plan with account automation
* this was just a display issue
* when a new plan is saved, ensure the appended `automatedCloudAccount` rule is persisted in the state of the `PlanList` component
Fixing issue when saving account management from plan form
* this is related to the issue fixed by #1086, but happens when saving from the plan form
* the fix is to filter down the rules in the `AccountManagement` when loading the plan
* if the plan is saved the correctly filtered rules for the …
=> Account automation bugfix

scripts/enable-aws-accounts/cf-kore-master-role.json, scripts/enable-aws-accounts/create-kore-master-role.sh
Resolves #1072 
Added a cloudformation template and a script to allow AWS Admins to create the kore role in the master account.
See the docs in the PR linked above but essentially:
```
./scripts/enable-aws-accounts/create-kore-master-role.sh --kore-user-arn arn:aws:iam::00000000:user/kore-accounts-test
[info]  stack bucket: kore-control-tower-cf-templates
[info]  stack name: kore-account-management-role (to create role of same name)
[info]  will grant sts permission to user:arn:aws:iam::00000000:user/kore-accounts-test
[info]  deploying stack - kore-account-management-role
[info]  waiting for stack to complete
[info]  Role successfuly created: kore-account-management-role …
```
=> add AWS CF template and script to create master account role

ui/__tests__/e2e/page-objects/configure/cloud/AWS/cluster-plans.js, ui/__tests__/e2e/page-objects/configure/cloud/AWS/cluster-policies.js, ui/__tests__/e2e/page-objects/configure/cloud/Azure/cluster-plans.js, ui/__tests__/e2e/page-objects/configure/cloud/Azure/cluster-policies.js, ui/__tests__/e2e/page-objects/configure/cloud/GCP/cluster-plans.js, ui/__tests__/e2e/page-objects/configure/cloud/GCP/cluster-policies.js, ui/lib/components/plans/PlanList.js, ui/lib/components/plans/custom/PlanOptionGKEVersion.js, ui/lib/components/plans/custom/PlanOptionVersion.js, ui/lib/components/plans/custom/index.js, ui/pages/configure/cloud/[...cloud].js
Use metadata service to constrain Kubernetes versions on the UI
Resolves #1049
* once a region is chosen, pull the available kubernetes versions from the metadata services
* expand the list of versions for GKE and EKS to include minor and patch versions, where appropriate
* maintain current functionality for GKE version, ie. only show if no release channel is selected
* lower case second words in cloud configure vertical tabs, for consistency
* adding alert description for AKS on plan list
**Choose region first**
**Expanded versions**
Please provide some CLI and/or manifest examples if relevant. This will help understand the changes and/or how to use …
=> Cluster plan versions from the metadata service

ui/lib/components/setup/CloudSetup.js, ui/lib/components/setup/ExistingCloudAccounts.js, ui/lib/components/setup/forms/RequestCredentialAccessForm.js, ui/lib/components/teams/cluster/MissingCredential.js, ui/lib/utils/cloud.js, ui/pages/setup/kore/cloud-access.js
I noticed some missing parts of the UI for Azure/AKS so I've fixed/added them
* adding AKS creds setup in `setup/kore/cloud-access`
* fixing missing credentials page for Azure when creating a cluster
* adding AKS credentials via setup pages at `setup/kore/cloud-access`
* working missing credentials page when trying to create an Azure cluster and no creds allocated
=> Adding missing parts of Azure/AKS support in the UI

.circleci/config.yml
The AKS cluster deletion can take more than 30 minutes, so we need to increase the timeout.
=> Increase the no_output_timeout to 60 minutes for the E2E tests

.circleci/config.yml, ui/scripts/install-e2e-deps.sh
Remove un-required dependencies and run UI E2E directly instead of inside Docker to speed up the build.
* Removes dependencies from all steps other than those which require them.
* Run the UI E2E directly instead of inside docker.
=> Remove un-required dependencies & run UI E2E directly

pkg/utils/cloud/aws/eks.go
On QA, the AWS api returns nil for the tags where no tags exist on the cluster. Handle this.
=> Fixup: handle nil tags from AWS API

pkg/utils/cloud/aws/eks.go
Second fix for nil pointers in the map of tags coming back from AWS... should address the panics in the QA env.
=> Fixup: Handle nil tags from AWS API (fix 2)

test/e2e/integration/aks-deletion.bats
It seems 30 minutes is not always enough for an AKS cluster to be deleted.
=> Increase the retry count for AKS deletion check in E2E

pkg/persistence/teams.go
The identifier for unidentified existing teams wasn't being persisted.
Completed:
* Checked in a new kore instance that teams are correctly having identifiers assigned where they previously existed without them.
=> Fixup: Ensure identifier persisted for team

ui/lib/components/costs/CostEstimate.js, ui/lib/components/plans/custom/PlanOptionVersion.js, ui/pages/teams/[name]/clusters/[cluster]/[tab].js
Adding cost estimates to already existing clusters
Resolves #1050
* removing redundant API request for service kinds on cluster page
* fixing plan values equality check in `CostEstimate` component - to prevent a refresh every time the component is updated
* removing unwanted console.log
Ensure kore is running with kore-costs feature enabled
Create a cluster, view the settings tab
See the costs
Edit some configuration eg add a node pool and see the cost estimate change
=> Adding cluster view/edit cost estimates

ui/__tests__/e2e/02-configure-cloud-gcp.test.js, ui/__tests__/e2e/03-configure-cloud-aws.test.js, ui/__tests__/e2e/04-configure-cloud-azure.test.js, ui/__tests__/e2e/page-objects/configure/cloud/cluster-plans-base.js, ui/__tests__/e2e/page-objects/configure/cloud/cluster-policies-base.js, ui/lib/components/credentials/AWSOrganization.js, ui/lib/components/credentials/Credentials.js, ui/lib/components/credentials/GCPOrganization.js, ui/lib/components/plans/ManageClusterPlanForm.js, ui/lib/components/plans/PlanItem.js, ui/lib/components/plans/PlanList.js, ui/lib/components/plans/custom/PlanOptionEKSNodeGroups.js, ui/lib/components/policies/PolicyForm.js, ui/lib/components/policies/PolicyList.js
Adding copy cluster plan functionality, along with the same for cluster policies for good measure 
Resolves #1015 
* adding a copy plan icon
* coping opens the new plan drawer with pre-filled data, which must be amended as required and saved
* an info alert informs the user what has happened
* amending edit/delete icons for resources, to be more consistent, with tooltips
* removing unused `processPlanCreateEdit` function in `PlanList` component
Copying cluster plans and policies
If you've created any related stories which should be done in the future (but not as part of this PR), please record it here.
=> Plan duplication

ui/lib/components/plans/PlanOption.js, ui/lib/components/plans/PlanOptionBase.js, ui/lib/components/plans/PlanViewEdit.js, ui/lib/components/plans/UsePlanForm.js, ui/lib/components/plans/custom/PlanOptionAKSNodePools.js, ui/lib/components/plans/custom/PlanOptionClusterMachineType.js, ui/lib/components/plans/custom/PlanOptionEKSNodeGroups.js, ui/lib/components/plans/custom/PlanOptionGKENodePools.js, ui/lib/components/utils/IconTooltip.js, ui/pages/teams/[name]/clusters/[cluster]/[tab].js
Adding functionality for GKE, EKS and AKS node pools/groups
Simplifying plan field visibility, for plan and node pools
Resolves #1146 
Field with `immutable=true` cannot be edited once the cluster is created
These fields are not shown on the drawer render, along with any fields that are not-editable according to the policy
I've introduced a switch on the node pool drawer, `Show all parameters`, which will display, in disabled mode, the non-editable and immutable field.
If a new node pool/group is created those fields will always be editable, until it's saved
The `Show read-only parameters` checkbox for a cluster plan has been changed to a switch, `Show …
=> Respect node pool/group field immutable flags on the UI and field visibility changes

charts/kore/templates/ingress.yaml, charts/kore/templates/kore.yml, charts/kore/templates/portal.yml, charts/kore/templates/secret.yaml, charts/kore/values.yaml, cmd/kore-apiserver/server.go, doc/development/api-enable-tls.md, doc/local-quick-start.md, pkg/client/client.go, pkg/client/config/config.go, pkg/client/config/types.go, pkg/client/fake/client.go, pkg/client/types.go, pkg/cmd/kore/local/helm.go, pkg/cmd/kore/local/providers/kind/kind.go, pkg/cmd/kore/local/up.go, scripts/kind_dev.sh, ui/.gitignore, ui/scripts/run-with-env.sh
This adds full https support to the kore API server. I've made changes to the Helm chart and the local run scripts, so the UI works with an untrusted CA in both cases.
The only case where we skip the certificate check is when `kore alpha local up` waits for the API server's `/healtz` endpoint, otherwise we always use the provided CA certificate.
* Generate a separate CA and server certificate for TLS
* Add `api.tls.enabled` and `api.tls.secretName` variables to Helm
* Bugfix: properly set the `TLSCert` and `TLSKey` config values from the API server CLI params.
* The CLI config can store an optional CA certificate for the API
* For https localhost API server URLs the `kore` CLI will automatically save the CA certificate when using `kore profiles configure` or `kore login`
* open port 10443 …
=> Allow to run the Kore API Server using HTTPS

pkg/cmd/kore/login/login.go
Backwards compatibility for CLI when talking to older Kore servers that don't support the auth methods endpoint.
=> Failback to SSO only if login methods endpoint not available.

.circleci/config.yml, Makefile, hack/verify-release-images.sh, ui/Makefile
The issue with having this set to the latest tag is those build of master SHOULD get master/latest else you can end up with weird edge cases due to the fact the tag is carried through to things like the images versions and the github release. This change should make it work as as expected i.e. if you build the binaries off master you get latest images and if you pull from a release it's tagged with an actual release version. 
Issue was hit by some people whom were trying out Kore, building binaries off master and hitting issues.
Resolves BUG
When building from master you get latest images. CircleCI passes the tag into the build and so binaries built from a tag trigger will have the version embedded.
NA
=> Defaulting to latest

.circleci/config.yml, ui/__tests__/e2e/02-configure-cloud-gcp.test.js, ui/__tests__/e2e/03-configure-cloud-aws.test.js, ui/__tests__/e2e/04-configure-cloud-azure.test.js, ui/__tests__/e2e/page-objects/base.js, ui/__tests__/e2e/page-objects/configure/cloud/cluster-plans-base.js, ui/__tests__/e2e/page-objects/utils.js, ui/__tests__/reporter.js, ui/jest.config.js
Fix for flakey plan/policy copy tests
* for some reason the drawer was not always showing
* the code shows that only the content of the drawer is conditional so this should be ok
* hack fix was to click the copy icon again if it failed
Attempted fix for `scrollIntoView` issues
* wait for the `#plan_config` and `#plan_summary` selectors before trying to scroll
Take screenshots of failed tests
* using the jasmine reporter
* uploading screenshots as artifacts on the CircleCI build
* example build with artifacts: https://app.circleci.com/pipelines/github/appvia/kore/4754/workflows/35284672-18f7-40bc-80e6-fe406d1b8716/jobs/21293/artifacts
=> Enhancements for UI e2e tests

pkg/controllers/korefeatures/costsfeature.go, pkg/controllers/secrets/gcp/reconcile.go, ui/lib/components/credentials/GCPOrganizationForm.js
The credentials for gke were renamed at some point it's not longer 'key' but 'service_account_key'
Resolves BUG
Tested using 'kore alpha local up' and adding the korefeature as documented
Was getting the below before changing in the secret 
```
{"controller":"services","error":"key \"key\" does not exist in secret kore-admin/appvia","file":"/go/src/github.com/appvia/kore/pkg/controllers/services/reconcile.go:104","func":"github.com/appvia/kore/pkg/controllers/services.(*Controller).Reconcile","level":"error","msg":"failed to reconcile the service","name":"kore-costs","namespace":"kore-admin","time":"2020-08-19T12:06:06Z"}
{"controller":"korefeatures","error":"\"kore-costs\" admin service has an error …
```
=> Kore Costs Key

ui/__tests__/e2e/page-objects/teams/index.js
Minor tweak to try to fix the latest failures.
The theory being that this timeout led to the errors showing in the logs
- team not deleted
- browser disconnected
=> Allow more time for cluster to load before trying to delete
