pkg/hub/users.go
- adding some audit of the users
=> Audit User

pkg/apiserver/allocations.go, pkg/apiserver/teams.go, pkg/hub/allocations.go
- adding an additional query param to retrieve allocations shared to you
=> Allocations

pkg/hub/codec.go, pkg/services/users/model/team.go
- adding the team summary back in
=> Team Summary

.circleci/config.yml
- removing the bits which dont need to be there
=> Tweaks to CircleCI

.circleci/config.yml
- adding the latest build and push back to circleci
=> Latest build

pkg/apiserver/plans.go, swagger.json
- fixing up the kind reference in the plans and the swagger
=> Swagger Fix

.circleci/config.yml
- adding a docker push to the workflow
=> Docker Push

pkg/hub/setup.go
- enabled a local user regardless
=> Enable Local User

pkg/apiserver/teams.go, swagger.json
=> API Fix Up

doc/cloud.md
- Minor corrections
- Added "coming soon" to supported upcoming cloud providers.
=> Doc spelling corrections and tidy up

pkg/hub/assets/plans.go
- adding the authorized master cidr's to the plans
=> Authorized Master CIDR

.gitignore, deploy/kube/api.yml, deploy/kube/apiserver.yml, deploy/kube/dex.yml, deploy/kube/etcd.yml, deploy/kube/mariadb.yml, deploy/kube/portal.yml, deploy/kube/redis.yml
- adding the kube deployment files
=> Deployment files

pkg/controllers/management/bootstrap/reconcile.go
=> Fix Dex Demo

.circleci/config.yml
- removing the swagger drift check for now, as it's debatable how useful
=> Swagger Drift

.circleci/config.yml
- fixing up the circleci build
=> CircleCI Build

pkg/apiserver/apiserver.go, pkg/apiserver/filters/not_implemented.go
- adding the no implementation
=> No Implementation

hack/dex.env
=> DEX Config

pkg/kore/config.go
- adding a check on the client scopes
=> Dex Scope Check

pkg/controllers/management/namespaceclaims/reconcile.go
- fixing up the namespace claim status
=> Namespace Status

pkg/cmd/korectl/delete.go
- adding the ability to delete by resource/kind on the cli
=> Delete by Hand

pkg/kore/gke.go
- fixing a bug with the delete
=> GKE Fix up

pkg/kore/clusters.go
- fixing the deletion of the cluster
=> Cluster Delete Fix

pkg/apiserver/helpers.go, pkg/cmd/korectl/requestor.go
- cleaning up the notfound on the cli
=> Clean Up Notfound

deploy/kube/dex-secret.example.yml, deploy/kube/dex.kubeconfig.example.yml
- adding some example deployment configs for dex
=> Dex Example Deployment Config

pkg/server/schema.go, pkg/server/server.go
- registering only what is required
=> Resource Registration

cmd/kore-apiserver/server.go
- fixing the command line option
=> Fix Options

cmd/kore-apiserver/options/options.go, pkg/apiserver/login.go
- adding the additional user claims
- ensuring the claims is consumed in the login
=> User Claims

pkg/controllers/management/bootstrap/assets.go, pkg/controllers/management/bootstrap/reconcile.go, pkg/utils/openid/discovery.go, pkg/utils/openid/types.go
- pulling the details from the discovery url
=> Discovery URL

pkg/cmd/auth-proxy/server.go, pkg/cmd/auth-proxy/types.go, pkg/controllers/management/kubernetes/proxy.go, pkg/utils/jwt.go
- fixing up the various bits of the proxy
=> Authentication Proxy

pkg/controllers/cloud/gcp/gke/bootstrap.go, pkg/kore/k8s_credentials.go
=> Kubernetes Creds

deploy/crds/clusters.compute.kore.appvia.io_kubernetescredentials.yaml, pkg/server/schema.go
- adding the crd and bypassing on the schema
=> Kubernetes Credentials

cmd/kore-apiserver/options/options.go, pkg/controllers/management/bootstrap/controller.go, pkg/kore/types.go
- feature gating the bootstrapping of the olm apps
=> Feature Gating Bootstrap

pkg/utils/kubernetes/bindings.go
- fixing the issue when the cluster roleRef has changed
- the field is immutable and the resource must be deleted before recreating
=> Cluster Role Bindings

Makefile
- nothing much here just cleaning up the output so there's less things
=> Makefile Output

cmd/auth-proxy/main.go, cmd/auth-proxy/options/options.go, pkg/cmd/auth-proxy/metrics.go, pkg/cmd/auth-proxy/server.go, pkg/cmd/auth-proxy/types.go, pkg/controllers/management/kubernetes/proxy.go
- adding metrics to the auth proxy
- adding prometheus scraping annotations
=> Auth proxy metrics

pkg/apiserver/login.go
=> Fix Debug Message

.gitignore, demo.env, doc/quick-start.md, hack/compose/demo.yml
- updating the demo docker compose to use a local .env file
- updating the docs to reflect the change
- @note this is waiting on https://github.com/appvia/kore-ui/pull/44 to be merged
- added the file to the gitignore to ensure no one accidentally commits
=> Demo Files

pkg/server/server.go
- as more and more controllers get added this is gonna become a burden on startup; backgrounding the registration and starting the api server
- fixes #101
=> Controller Registration

examples/gke-cluster.yml, pkg/controllers/management/kubernetes/reconcile.go
- fixing the credentials message
=> Credentials

pkg/controllers/cloud/gcp/gke/gke_client.go
- enabling network policies for gke
=> Enable Network Policies for GKE

pkg/controllers/management/clusterconfig/reconcile.go
- fixing the the params for the cluster config (note these are not being used for now)
=> Fix Cluster Config Params

pkg/controllers/cloud/gcp/gke/reconcile.go
=> reconcile kubernetes client  secret

pkg/controllers/cloud/gcp/gke/gke_client.go
- adding the managed cloud nat
=> GKE Cloud NAT

pkg/controllers/cloud/gcp/gke/gke_client.go, pkg/controllers/cloud/gcp/gke/reconcile.go
- ensuring regardless of cluster existence the cloud-nat and networking is created
=> Reconcile GKE

Makefile
- adding a spelling check on the builds
=> Spelling Checks

cmd/kore-apiserver/options/options.go, cmd/kore-clusterappman/main.go, pkg/cmd/defaults.go
- defaulting to json logging
- need to do the same for the kore-apiserver as well
=> JSON Logging

pkg/clusterappman/clusterappman.go, pkg/clusterappman/helpers.go, pkg/controllers/management/kubernetes/clusterappman.go, pkg/controllers/management/kubernetes/reconcile.go
=> Report final status

Makefile
- ensuring we exit with a failure one a binary fails to build
=> Makefile Exit

doc/quick-start.md, examples/gke.yml
- adding some comments to the example cluster
=> Example Cluster

hack/compose/demo.yml, pkg/kore/assets/plans.go
Merging this one now has a previous merge around switching private networking broke master
=> Bumping demo

cmd/korectl/main.go, pkg/cmd/korectl/auth.go, pkg/cmd/korectl/commands.go, pkg/cmd/korectl/config.go, pkg/cmd/korectl/contexts.go, pkg/cmd/korectl/helper.go, pkg/cmd/korectl/kubeconfig.go, pkg/cmd/korectl/requestor.go, pkg/cmd/korectl/types.go
- adding a contexts to the cli
=> CLI Context

pkg/controllers/cloud/gcp/gke/gke_client.go
Fixes an issue where incorrectly configured provider credentials would cause the apiserver to panic and exit.
=> Prevent apiserver from panicking when provider credentials are incorrect

pkg/cmd/korectl/types.go
- the marshalling is causing an issue and dropping fields
=> Fix Struct Fields

pkg/apiserver/audit.go, pkg/apiserver/health.go, pkg/apiserver/idp.go, pkg/apiserver/login.go, pkg/apiserver/plans.go, pkg/apiserver/teams.go, pkg/apiserver/users.go, pkg/apiserver/whoami.go, pkg/cmd/auth-proxy/server.go, pkg/cmd/korectl/clusters.go, pkg/cmd/korectl/contexts.go, pkg/cmd/korectl/delete.go, pkg/cmd/korectl/helper.go, pkg/cmd/korectl/kubeconfig.go, pkg/cmd/korectl/requestor.go, pkg/cmd/korectl/teams.go, pkg/controllers/management/clusterconfig/controller.go, pkg/services/users/store.go, pkg/store/informer/metrics.go, pkg/utils/openid/discovery.go
Fixes a number of spelling/grammar issues throughout
=> Correct spelling and grammar issues

pkg/controllers/management/kubernetes/reconcile.go
- removing for now as it throws up an error when there isn't one
=> Dropping Early Status

pkg/clusterapp/clusterapp.go, pkg/controllers/cloud/gcp/gke/reconcile.go, pkg/controllers/management/clusterbindings/reconcile.go, pkg/controllers/management/clusterroles/delete.go, pkg/controllers/management/clusterroles/reconcile.go, pkg/controllers/management/kubernetes/delete.go, pkg/controllers/management/kubernetes/reconcile.go, pkg/controllers/management/namespaceclaims/delete.go, pkg/controllers/management/namespaceclaims/reconcile.go, pkg/controllers/management/podpolicy/reconcile.go, pkg/controllers/user/allocations/reconcile.go, pkg/controllers/user/teams/delete.go, pkg/controllers/user/teams/reconcile.go
=> Human readable messages and constants for component names

hack/setup/instances/gke-cluster.yml
- removing the private networking from this
=> Fix Instance GKE

pkg/cmd/auth-proxy/server.go
- fixing the auth proxy for upgrade connections
=> Auth Proxy

pkg/clusterappman/manifests/captain/README.md, pkg/clusterappman/manifests/captain/captain.yaml
These were indented wrong which made manual testing hard, fixed and bumped version.
=> Fix captain manifests

pkg/controllers/management/kubernetes/proxy.go
- upgrading the release of the auth proxy
=> Proxy Release

cmd/korectl/main.go, pkg/cmd/korectl/auth.go, pkg/cmd/korectl/config.go, pkg/cmd/korectl/local.go, pkg/cmd/korectl/profiles.go, pkg/cmd/korectl/types.go
- An additional PR which does a complete rename 
- Waiting for https://github.com/appvia/kore/pull/227 to merge first
=> Change context

cmd/korectl/main.go, cmd/korectl/options/options.go, pkg/apis/clusters/v1/doc.go, pkg/apis/config/v1/doc.go, pkg/apis/config/v1/plan_types.go, pkg/apis/core/v1/doc.go, pkg/apis/gke/v1alpha1/gke_types.go, pkg/apis/gke/v1alpha1/gkecredentials_types.go, pkg/apis/org/v1/doc.go, pkg/apis/org/v1/team_types.go, pkg/apis/org/v1/user_types.go, pkg/cmd/doc.go, pkg/cmd/korectl/auth.go, pkg/cmd/korectl/helper.go, pkg/cmd/korectl/types.go, pkg/version/authors.go, pkg/version/version.go, pkg/version/version_test.go
Copyright info to be the same across all source files.
=> Copyright fix

pkg/apiserver/login.go
Prevents an attack on our openid configuration by ensuring that the apiserver only ever redirects to localhost or 127.0.0.1
=> Prevent dangerous oauth redirects

pkg/cmd/korectl/requestor.go
- fixes an issue in the values when the items is null
=> Fix Zero/Nil Items

pkg/cmd/korectl/resource.go
- adding the resource config for the gkes resource type
- alphabetically sorting the resource configs
=> GKE Resource Config

pkg/cmd/korectl/requestor.go
* Add RequestError object to have errors with status codes (easier check in Exists)
* Remove the custom responseHandler as it wasn't used and was added prematurely
* Remove os.Exits and custom error printing, so we can handle all errors the same way in the CLI
=> Requestor improvements and cleanup

pkg/cmd/korectl/create.go, pkg/cmd/korectl/create_cluster.go, pkg/cmd/korectl/create_namespace.go, pkg/cmd/korectl/delete.go, pkg/cmd/korectl/edit.go, pkg/cmd/korectl/errors.go, pkg/cmd/korectl/get.go, pkg/cmd/korectl/helper.go, pkg/cmd/korectl/requestor.go, pkg/cmd/korectl/teams.go
Various CLI improvements:
* long descriptions for create/get/edit/delete + fix command templates
* better errors
* check whether a team exists when adding/removing members
=> CLI improvements

pkg/apis/gke/v1alpha1/gkecredentials_types.go, pkg/apis/gke/v1alpha1/zz_generated.deepcopy.go, pkg/apis/gke/v1alpha1/zz_generated_openapi.go, pkg/cmd/korectl/delete.go, pkg/controllers/cloud/gcp/gkecredentials/reconcile.go, pkg/register/assets.go
I introduced a bug in the gke credentials with omitempty
=> Fix GKE Credentials

pkg/cmd/korectl/delete.go, pkg/cmd/korectl/profiles.go
- until we fix the delete command we should probably remove this subcommand for now as its still
available via the ui
=> Fix Delete

pkg/cmd/korectl/commands.go, pkg/cmd/korectl/logout.go
To delete the auth credentials from the current profile:
```
korectl logout
```
To delete the auth credentials from the select profile:
```
korectl logout prod
```
=> Add logout command

Makefile
When we do `make docker-release` we did skip pushing the proxy - this fixes that.
=> ensure we build all images

pkg/kore/assets/plans.go
- updating the plan version but need a better way of doing this in general
=> Update Plan Version

.gitignore, Makefile, hack/bin/http_test.sh
It was annoying me - curl kept on exiting with Error 52 (empty response) as both Kube API and Kore API answer a little bit snappily...
=> fix make run

examples/gke-cluster.yml, examples/gke.yml, hack/compose/demo.yml, pkg/cmd/korectl/create_cluster.go
- bumping the version of the api to v0.0.16
- bumping the version of the ui to v0.0.6
=> Demo Release

hack/compose/kube.yml
- just fixing the tags we are using to ensure repeative builds / errors etc
=> Container Versions

README.md
- fixing the link in the readme to quick start (the file was renamed)
=> Quick Start Readme Link

charts/kore/templates/kore.yml, charts/kore/templates/portal.yml, charts/kore/values.yaml, doc/install-kore-in-kind.md
I've introduced the hostPort parameter so we can expose the container ports on the host
I've added detailed instructions in `doc/install-kore-in-kind.md`
=> Run Kore in Kind

hack/bin/http_test.sh
Shamefully bad bash on my part. Tested by change last time.
=> fixup for bad bash in curl wait

doc/alpha-local-quick-start.md
- ensuring the user has enabled the apis
- related to ticket https://github.com/appvia/kore/issues/286
=> Enable APIs

charts/kore/templates/kore.yml
- the api needs to know the ui endpoint for invitations
=> UI Endpoint

pkg/controllers/cloud/gcp/gke/gke_client.go, pkg/controllers/cloud/gcp/gke/reconcile.go, pkg/controllers/cloud/gcp/gke/types.go
- as some people might still be using the old version, with the region from credentials
=> Bug Fix GKE Region

pkg/cmd/korectl/create_cluster.go
I've added the plan-param flag to the create cluster command. It expects the following format:
```
--plan-param=<JSON value>
```
Example:
```
create cluster --team a-team andras-test --plan gke-development --allocation gke --plan-param authorizedMasterNetworks='[{"name":"home", "cidr": "1.2.3.4/32"}]' --plan-param diskSize=200
```
The parser only allows existing values with the same type.﻿
This is useful for https://github.com/appvia/kore/pull/335 - setting the `authorizedMasterNetworks` and `authProxyAllowedIPs` parameters for a new cluster:
```
korectl create cluster \
--team a-team andras-test \
--plan gke-development \
--allocation gke \
--plan-param authorizedMasterNetworks='[{"name":"home", "cidr": "1.2.3.4/32"}]' \
--plan-param authProxyAllowedIPs='["1.2.3.4/32"]'
```
This is for …
=> Provide a way to override plan parameters when creating a cluster (CLI)

pkg/controllers/cloud/gcp/gke/gke_client.go
- appears that when it wasn't able to find the clusters, it doesn't throw an error but has a nil response .. a bit crap, i'd of assumed the Clusters slice would have just been empty
=> Potential Segmentation Fault

pkg/cmd/korectl/create_cluster.go, pkg/cmd/korectl/create_namespace.go, pkg/cmd/korectl/create_secret.go
- trying to keep the usage consistent
=> Long Description Format

cmd/korectl/main.go, pkg/cmd/app.go, pkg/cmd/korectl/config.go, pkg/cmd/korectl/profiles.go
- adding a delete command to profile
- in the process taking the opportunity to clean up the code
de09d927 Profile Delete Command
7cbb7d84 - allows you to switch profiles when one is not configured
=> Profile Delete Command

charts/kore/values.yaml, hack/compose/demo.yml
- moving back to v0.0.6 as we had an error
=> Kore UI Tag v0.0.6

pkg/controllers/cloud/gcp/gke/reconcile.go
=> fix invalid gke status when no credentials

pkg/cmd/korectl/apply.go, pkg/cmd/korectl/helper.go, pkg/utils/file.go
- adding the feature as it was useful for testing purposes and copy and paste
- @note: not too sure about the method naming here so if anyone has a better name, please say
=> Apply from Stdin

Makefile
- the `$${DOCKER_IMAGES}` wasn't resolving so was getting an empty string (not sure if this a linux thing), though i'm guessing the single dollar works for all?
=> Makefile Images Stage Fix

cmd/korectl/options/options.go, pkg/cmd/app.go, pkg/cmd/korectl/create_allocation.go, pkg/cmd/korectl/create_cluster.go, pkg/cmd/korectl/create_gcp_organization.go, pkg/cmd/korectl/create_gcp_projectclaim.go, pkg/cmd/korectl/create_member.go, pkg/cmd/korectl/create_namespace.go, pkg/cmd/korectl/create_secret.go, pkg/cmd/korectl/create_team.go, pkg/cmd/korectl/helper.go, pkg/cmd/korectl/resource.go, pkg/cmd/korectl/teams.go
- cleaning up the code and reducing the dup
- adding a wait on resource for most of the resources
=> CLI Cleanup & Resource Waits

pkg/controllers/cloud/gcp/gke/reconcile.go, pkg/controllers/management/kubernetes/reconcile.go
- the check of the cloud provider was not working correctly and leaving the Kubernetes type in a pending state
- adding states for all
=> Fix Cloud Provider failing state

pkg/kore/teams.go
- the denial was being thrown without a message
=> Team Removal with Clusters Bug

ui/Makefile, ui/scripts/run-dev.sh, ui/scripts/run-prod.sh
Fixes my messing up of the make run and make run-prod targets - the environment was not being set up correctly into node. This works, could probably be improved further.
=> Fix UI make run and run-prod targets

go.mod, go.sum, vendor/github.com/sirupsen/logrus/.golangci.yml, vendor/github.com/sirupsen/logrus/.travis.yml, vendor/github.com/sirupsen/logrus/README.md, vendor/github.com/sirupsen/logrus/entry.go, vendor/github.com/sirupsen/logrus/exported.go, vendor/github.com/sirupsen/logrus/go.mod, vendor/github.com/sirupsen/logrus/go.sum, vendor/github.com/sirupsen/logrus/json_formatter.go, vendor/github.com/sirupsen/logrus/logger.go, vendor/github.com/sirupsen/logrus/logrus.go, vendor/github.com/sirupsen/logrus/terminal_check_bsd.go, vendor/github.com/sirupsen/logrus/terminal_check_js.go, vendor/github.com/sirupsen/logrus/terminal_check_unix.go, vendor/github.com/sirupsen/logrus/text_formatter.go, vendor/github.com/sirupsen/logrus/writer.go, vendor/modules.txt
Addresses #330 (file and func context being wrong in log messages).
=> Update logrus. 

pkg/cmd/korectl/helper.go
- fixing the bugs which wasn't incrementing the attempts
=> Fix Max Attempts on Resource Waits

pkg/kore/assets/plans.go
- we need to bump the version in the plan
=> GKE Release Versions

pkg/cmd/korectl/create_secret.go, pkg/controllers/secrets/generic/reconcile.go
e280bcf4 Secrets Bug Fix
ac6e2870 - ensuring we default to success on generic
=> Fix secrets

.circleci/config.yml, ui/Makefile
Move the complexity of how to build/test into the makefile.
=> Minor tweaks to simplify UI circle CI steps

.circleci/config.yml, hack/compose/kube.yml
- switching to the gcr.io registry
- updating to v1.15.11 stable
780f5c68 Kubernetes Images
4c412207 - updating the same images in the circleci as well
=> Kubernetes Images

.circleci/config.yml
- bumping the version of golang to v1.14 (now the logrus issue has been resolved)
=> Golang Version v1.14

ui/lib/components/forms/NewTeamForm.js, ui/lib/utils/kore-api-client.js, ui/lib/utils/kore-api.js, ui/pages/index.js, ui/pages/teams/new.js
Next step would be to auto-gen the KoreApiClient class.
=> Intellisense support for the UI API

pkg/apiclient/operations/add_team_member_parameters.go, pkg/apiserver/apiserver_integration_test.go, pkg/apiserver/teams.go, ui/__tests__/pages/_app.test.js, ui/lib/components/SiderMenu.js, ui/lib/utils/kore-api-client.js, ui/lib/utils/kore-api.js, ui/lib/utils/redirect.js, ui/pages/_app.js, ui/pages/index.js, ui/server/controllers/session.js, ui/server/routes.js, ui/server/services/org.js
* as discussed these are just listed down the left side menu
* we can adapt if this becomes too cumbersome
* the implementation keeps the user teams and other teams separate in the data so that we can change the approach easily if we decide to
=> Show all teams if user is admin

.circleci/config.yml
- changing it was we just wait on the two releases
=> QA Release Deps

pkg/kore/assets/plans.go
=> GKE Kubernetes Version

test/e2e/integration/users.bats
- bringing the check in now the fixes have been merged
=> Admin User Check

ui/__tests__/pages/_app.test.js, ui/lib/components/forms/AuthConfigForm.js, ui/lib/components/forms/ClusterBuildForm.js, ui/lib/utils/api-request.js, ui/lib/utils/kore-api-client.js, ui/lib/utils/redirect.js, ui/pages/_app.js, ui/pages/login.js, ui/pages/setup/authentication/github/index.js, ui/pages/setup/authentication/google/index.js, ui/pages/setup/kore/cloud-providers/index.js
* now passing the next router into the function
* this is the same as passing the server-side response
* fixes the issue with requiring `next/router` and makes more sense anyway
* refactoring all function calls also
Fixes #481
=> Refactoring redirect helper function

pkg/apiserver/login.go
The currrent implementation was only setting the redirect_url in the authorize handler. This meant when the request went across a pod, you'd send an invalid token exchange as the redirect_url wouldn't have been set. I've kept the functionality of using the host headers as this is quiet useful if your reverse proxying things.
```shell
[kore-apiserver-5b9b845759-pztwg] {"client_ip":"10.56.1.5:45036","file":"/go/src/github.com/appvia/kore/pkg/apiserver/login.go:155","func":"github.com/appvia/kore/pkg/apiserver.(*loginHandler).authorizerHandler","level":"info","msg":"providing authorization redirect to identity service","redirect_url":"https://XXXXXXXX/oauth/callback","scopes":"email,profile,offline_access","time":"2020-04-07T22:16:31Z"} 
[kore-apiserver-5b9b845759-pztwg] …
```
=> Oauth Redirect URL Bug Fix

charts/kore/values.yaml
- the default values was missing an empty images map
=> Helm Chart Fix Images

pkg/kore/clusters.go, pkg/kore/plans.go
Related to https://github.com/appvia/kore/issues/346
=> Cluster kind/plan should not be updated, do not allow to delete plans with existing clusters

hack/compose/demo.yml
- bumping the local demo version (we should probably just switch this to latest now)
=> Local Demo Version v0.0.22

charts/kore/values.yaml
- bumping to the correct version now
=> Helm Chart Version

test/e2e/integration/gke.bats, test/e2e/integration/users.bats
- just fixing up a check on the deletion of admin
=> E2E Checks

pkg/cmd/korectl/resource.go
- fixing up the reference to the status in the resource from korectl
=> EKS VPC Status

pkg/apiclient/models/v1alpha1_infra.go, pkg/apis/eks/v1alpha1/eksvpc_types.go, pkg/apis/eks/v1alpha1/zz_generated.deepcopy.go, pkg/controllers/cloud/aws/eksvpc/reconcile.go, pkg/register/assets.go, pkg/utils/cloud/aws/types.go, pkg/utils/cloud/aws/vpc_client.go, ui/kore-api-swagger.json
=> provide the public EIP status on the VPC object

pkg/controllers/management/cluster/controller.go, pkg/controllers/management/cluster/delete.go, pkg/controllers/management/cluster/helper.go, pkg/controllers/management/cluster/reconcile.go, pkg/server/server.go
- justing adding some comments
=> Adding Comments

Makefile
I thought this was there already, just adding an docker pull to ensure the correct images. Also dropping the operators for now as weren't not using it.
=> Ensure Demo Pull

pkg/controllers/user/allocations/reconcile.go
- using a status.patch() rather than update()
- fixing up the logging to remain consistent
=> Fix Allocations Controller Status

ui/kore-api-swagger.json, ui/lib/components/plans/PlanOption.js, ui/lib/kore-api/model/V1alpha1EKSSpec.js, ui/lib/kore-api/model/V1alpha1EKSVPCSpec.js, ui/lib/kore-api/model/V1alpha1Infra.js
* also updating swagger and models
=> Fixing error with PlanOption

pkg/controllers/management/namespaceclaims/delete.go, test/e2e/integration/namespaces.bats
Not sure who this went unnoticed but the namespace wasn't being deleted. I've fixed the error and added a check
=> Namespace Delete Bug

pkg/cmd/kore/kore.go
- a quick fix for pulling in defauld team into the cli
=> Fix Default Team Suggestion

pkg/cmd/kore/kore.go, pkg/cmd/utils/handler.go
- pushing the default team into the cli (used to suggestions as these retrieve the flags pre-context)
=> Default Team

pkg/utils/cloud/aws/tags.go
Add retry mechanism when tagging AWS resources.
The AWS API is eventually consistent and sometimes it takes time to newly created resources to exists when tagging.
The API can return errors like this:
```
"error tagging new aws routetable bootstrap-eks-production-Public-Routes-Internet,
id rtb-029d7351fdee7bea6 - InvalidRouteTableID.NotFound: The routeTable ID
'rtb-029d7351fdee7bea6' does not exist\n\tstatus code: 400, request id: 32a61690-57ff-47c4-9400-0e8e4b1a0b6d"
```
In this specific case probably it's more valuable to have a built-in retry as to handle retries in various reconcile loops.
As a reference this is how Terraform handles this: https://github.com/terraform-providers/terraform-provider-aws/blob/783133790808672670a1fa1745632cc1583c56a6/aws/internal/keyvaluetags/create_tags_ge …
=> Add retry mechanism when tagging AWS resources

pkg/cmd/kore/profiles/list.go, pkg/utils/render/format.go
- showing the active profile in the list command to make things clearer
=> Active Profile

test/e2e/integration/gke-deletion.bats
- sometimes takes a little longer to switch
=> Deletion Status

pkg/cmd/errors/errors.go, pkg/cmd/utils/factory.go
d913f25e Method Not Allowed
c152f9be - changing the wording somewhat
```shell
[jest@starfury kore]$ kore edit kubernetes -t devx devx-gke-development 
Error: operation not permitted on the resource
```
=> Method Not Allowed 

ui/pages/index.js
=> Amending home page to show AWS account credentials in stats

hack/deploy-qa.sh, hack/deploy.sh
=> generic deploy

test/README.md, test/e2e/integration/auth-proxy.bats
d21954f0 Auth Proxy Checks
2ccd8169 - fixing the readme
=> Authentication Proxy E2E Additional Checks

.circleci/config.yml, hack/deploy-qa.sh, pkg/cmd/kore/create/admin.go, pkg/cmd/kore/delete/delete_admin.go, test/e2e/environment.sh, test/e2e/integration/gke-deletion.bats, test/e2e/integration/namespaces.bats, test/e2e/integration/users.bats
- fixes the creation and deletion of admins
=> Admin Fixes

hack/deploy.sh
=> Deployment Fix

pkg/cmd/kore/apply/apply.go
- fixing the apply command to use either the selected team or override on the namespace of the resource
=> Apply Command Fix

pkg/apiserver/clusters_integration_test.go, pkg/apiserver/plans_integration_test.go, pkg/cmd/kore/create/cluster.go, pkg/kore/assets/plan_schema_eks.go, pkg/kore/assets/plan_schema_gke.go, pkg/kore/assets/plans.go, test/e2e/integration/auth-proxy.bats
- fixing the team role in the cluster build
=> Cluster Default Team Role

doc/alpha-local-quick-start.md, doc/install-kore-in-kind.md, doc/install.md, doc/security-gke.md, pkg/client/config/types.go, pkg/cmd/kore/create/secret.go, pkg/cmd/kore/get/get.go, pkg/cmd/kore/local/local.go, pkg/cmd/kore/local/logs.go, pkg/cmd/kore/local/start.go, pkg/cmd/kore/local/stop.go, pkg/cmd/kore/login/login.go, pkg/cmd/kore/profiles/delete.go, pkg/cmd/kore/profiles/profiles.go, pkg/cmd/kore/profiles/set.go, pkg/cmd/kore/profiles/use.go, ui/README.md, ui/pages/teams/[name].js, ui/scripts/run-dev.sh, ui/scripts/run-prod.sh
- switching the docs over to using the kore cli
- swithcing the default config dir to ~/.kore/config
=> Replace korectl references with kore in docs

.circleci/config.yml, hack/deploy-qa.sh, hack/deploy.sh
A minor change; pulling in the ENVIRONMENT and explicitly checking the variables have been set
=> QA Release

pkg/client/client.go
This is a regression from korectl, we should handle validation errors returned from the API.
Before:
```
$ kore apply --team a-team -f ./examples/eks.yml
Error: "test-eks-dev" failed validation
```
After:
```
$ kore apply --team a-team -f ./examples/eks.yml
Error: "test-eks-dev" failed validation:
* plan: "test-eks-plan" does not exist
```
=> Handle validation errors in kore

ui/lib/components/team/EKSCredentials.js, ui/lib/components/team/GCPOrganization.js, ui/lib/components/team/GKECredentials.js
* instead of `eye` which is used for viewing
=> Using edit icon for edit

charts/kore/templates/portal.yml, hack/deploy-qa.sh, hack/deploy.sh
* enabling prototypes on QA env
* default this to false for all other deploys
=> Set KORE_UI_SHOW_PROTOTYPES to true on QA env

charts/kore/templates/portal.yml, hack/deploy-qa.sh, hack/deploy.sh
=> [BUG] Chart Fix

.circleci/config.yml, .gitignore, test/e2e/check-suite-units.sh, test/e2e/check-suite.sh, test/e2e/environment.sh, test/e2e/integration/auth-proxy.bats, test/e2e/integration/clusterappman.bats, test/e2e/integration/clusterconfig.bats, test/e2e/integration/clusterroles.bats, test/e2e/integration/eks-deletion.bats, test/e2e/integration/eks.bats, test/e2e/integration/gke-deletion.bats, test/e2e/integration/gke.bats, test/e2e/integration/helper.bash, test/e2e/integration/namespaces.bats, test/e2e/integration/plan-policies.bats, test/e2e/integration/profiles.bats, test/e2e/integration/safeguards.bats, test/e2e/integration/teardown.bats, test/e2e/plan-policies.bats, test/trigger-e2e.sh
Replicating the checks for GKE on to EKS
Ensure you have a personal CircleCI token exposed as `CIRCLECI_TOKEN`
`$ test/trigger-e2e.sh --enable-gke  --enable-eks`
EKS takes long and should be complete in 30/40 minutes. GKE is usually done in 8/12
=> EKS E2E Testing

.circleci/config.yml, CHANGELOG.md, Makefile, go.mod, hack/build/tools/awesome-release-logger/main.go, hack/build/tools/github-issues/github-issues.go
So first checkin correctly detects the missing release notes and the second checks in the generated raw. Happy for release note comments / edits here...
=> add check for release notes (and generator)

pkg/client/client.go, pkg/client/config/config.go, pkg/client/helper.go, pkg/cmd/errors/errors.go, pkg/cmd/utils/factory.go, pkg/utils/reflect.go, pkg/utils/reflect_test.go
Currently the client will blindly use the config without checking anything, is add's an error type and checks for the first thing (endpoint)
=> Client Profile Configuration

doc/local-quick-start.md
Couple of super-minor changes to the quick start.
=> Quick start fixes: duplicated 'Note', update CLI to v0.1.0

pkg/cmd/kore/local/configure.go
A recently caused this issue where by the local configure is now overwriting other authinfos
=> Local Configure

ui/assets/styles.less, ui/pages/_app.js
=> Amending version to make appear at the bottom regardless of page height

pkg/client/config/types.go
Adding the omitempty to remove the unrequired fields
=> OmitEmpty YAML tags

README.md
The wording here is a bit out of date and duplicated what is covered in more detail in the local quick start, just tidied it up a bit.
=> Minor tweak to README.md

test/e2e/integration/eks.bats
=> [BUG] EKS E2E Fix

pkg/cmd/kore/create/secret.go
- fixing the bug in creating the secret
=> [BUG] Kore CLI Secrets

.circleci/config.yml
Adding a nightly trigger to kick off the E2E on Monday to Friday
=> Nightly GKE E2E

pkg/apiclient/models/v1alpha1_e_k_s_credentials_spec.go, pkg/apiclient/models/v1alpha1_g_k_e_credentials_spec.go, pkg/apis/eks/v1alpha1/ekscredential_types.go, pkg/apis/gke/v1alpha1/gkecredentials_types.go, ui/kore-api-swagger.json, ui/lib/kore-api/model/V1SecurityScanResultSpec.js, ui/lib/kore-api/model/V1alpha1EKSCredentialsSpec.js, ui/lib/kore-api/model/V1alpha1GKECredentialsSpec.js
Testing locally at the moment, will update PR once tested.
=> Fixup: make CredentialsRef omitempty on GKE and EKS creds

test/e2e/integration/eks-deletion.bats, test/e2e/integration/eks.bats, test/e2e/integration/gke-credentials.bats
Sending the output to /dev/null
=> CI Output /dev/null

pkg/controllers/security/controller.go, pkg/controllers/security/reconcile.go, pkg/kore/security.go, pkg/security/authproxyips.go, pkg/security/authproxyips_test.go, pkg/security/rule_helpers.go, pkg/security/scanner.go, pkg/security/types.go
- passing down the context and a kubernetes client
- @question should we pass the client.Client or kore.Interface? or both
=> Security Rules - Context & Client

pkg/controllers/security/reconcile.go
Just fixing up the logging were I saw it. The use of the comma doens't give a whitespace so you end up wuth 'attempting to reconcile the security scans forCluster'
=> Security Controller Logging

.circleci/config.yml
- adding the EKS build to the night e2e
=> EKS Nightly

pkg/kore/accounts.go
The current implementation doesn't correctly allow for updating the CRD as it's missing the patch option
=> [BUG] Fix Update Accounting CRD

charts/kore/templates/kore.yml, charts/kore/templates/portal.yml, charts/kore/values.yaml, hack/deploy-qa.sh, hack/deploy.sh
- adding the ability to enable feature gates on the ui and api
=> Helm Charts - Enabling Feature Gates

pkg/apis/security/v1/security_scan_types.go, pkg/apis/security/v1/zz_generated.deepcopy.go, pkg/controllers/security/controller.go, pkg/kore/codec.go, pkg/kore/security.go, pkg/security/authproxyips.go, pkg/security/gke_autoscaling.go, pkg/security/gke_autoscaling_test.go, pkg/security/scanner.go, pkg/security/types.go
Adding a first check for checking the autoscaling feature on clusters and plans
=> GKE Autoscaling Rule

pkg/security/gke_autorepair.go, pkg/security/gke_autorepair_test.go, pkg/security/gke_autoscaling.go, pkg/security/rule_helpers.go, pkg/security/scanner.go
- adding another simple check to indicate the status of the auto repair
=> GKE Auto Repair Security Check

pkg/security/gke_autorepair.go, pkg/security/gke_autoscaling.go, pkg/security/rule_helpers.go
- Adding the message back to the result
=> Security Result Message

pkg/controllers/management/kubernetes/delete.go, pkg/controllers/management/kubernetes/ensure.go
I introduced a bug where the finalizer was being removed too quickly
=> Kubernetes Finalizer Removal Bug

Makefile, charts/kore/templates/kore.yml, cmd/kore-apiserver/options/options.go, cmd/kore-apiserver/server.go, hack/bin/run-api-with-kind.sh, hack/bin/run-api.sh, hack/compose/database.yml, hack/compose/kube.yml, pkg/clusterappman/deploy.go, pkg/controllers/management/kubernetes/clusterappman.go, pkg/controllers/management/kubernetes/helper.go, pkg/controllers/management/kubernetes/reconcile.go, pkg/controllers/management/kubernetes/types.go, pkg/kore/types.go, pkg/server/server.go
This will allow us to start managing dependencies in the kore cluster.
Will address first part of #751
=> start clusterappman with api-server

Makefile, charts/kore/templates/kore.yml, charts/kore/templates/portal.yml, doc/install-kore-in-kind.md, scripts/kind_dev.sh, ui/Dockerfile.dev
* Add a dev image for the UI and use it if the version is set to dev.
* Add a script and make target to easily start up the kind cluster
=> Support development fully with kind

.circleci/config.yml, pkg/controllers/cloud/aws/eks/delete.go, pkg/controllers/cloud/aws/eks/ensure.go, pkg/controllers/cloud/aws/eksnodegroup/delete.go, pkg/controllers/cloud/aws/eksnodegroup/ensure.go, pkg/kore/clusters.go, pkg/utils/cloud/aws/iam.go, test/e2e/check-suite.sh, test/e2e/integration/eks-deletion.bats, test/e2e/integration/eks.bats
The current implementation is not removing the IAM roles from the EKS NodeGroup and Cluster. I've added tests for both and ensured the roles are removed.
=> Ensure IAM Roles Removal

.circleci/config.yml, hack/deploy-demo.sh
* using the helm chart as per the deploy to the QA env
* renaming `release-qa` to `deploy-qa` in CircleCI config
=> Adding approval for deploy to demo

pkg/controllers/security/delete.go, pkg/controllers/security/reconcile.go, pkg/kore/clusters.go, pkg/kore/plans.go
- fixing up the deletion of the scans by archiving the deleted
=> Security Scan Deletion

Makefile, ui/lib/components/security/SecurityScanResult.js, ui/lib/components/services/ServiceAdmin.js, ui/lib/components/services/ServiceProvider.js, ui/lib/kore-api/kore-api-client.js, ui/pages/configure/cloud.js, ui/pages/teams/[name].js
=> UI - Admin Enable / Disable AWS Cloud Services

ui/lib/components/plans/PlanList.js, ui/lib/components/resources/ResourceList.js
Fixes issue where you can't navigate out from the plan view accessed from the plan list.
=> Fixup - Plan viewer not working correctly from plan list

pkg/kore/service_credentials.go, pkg/kore/services.go, ui/lib/components/plans/UsePlanForm.js, ui/lib/components/teams/service/ServiceCredentialForm.js
Fixes https://github.com/appvia/kore/issues/872
=> Allow to delete a service when there are no service credentials for that service

ui/lib/components/services/ServiceKindList.js
* no need to load the whole list again if one is enabled/disabled
* once the API call is successful replace the amended service in the state with the one returned from the API, then sort the list
* more easily allows a user to enable/disable multiple services quickly
* also handle an error updating the service
=> Minor cloud service management UX improvement

charts/kore/templates/ingress.yaml
- fixing the ingress api group in the chart
=> Ingress API Group

ui/lib/components/teams/service/ServicesTab.js, ui/pages/teams/[name]/services/[service].js
* show a warning modal which lists the access that must be removed first
Fixes #923
=> Prevent deletion of a cloud service if credentials exist

ui/pages/configure/users.js
* also updating the users component to user the KoreApi
=> Fix up issue with revoking admin from a user

ui/.babelrc, ui/package.json
* also amending name and license in package.json
=> Fixing styles not loading properly

ui/.babelrc, ui/package-lock.json, ui/pages/_app.js
* removing `styled-jsx/babel` plugin as it seems to make no difference
* including a missing update to package-lock.json
=> Import ant styles in an attempt to prevent the loading issue

.circleci/config.yml, ui/Makefile, ui/__tests__/e2e/02-configure-cloud-gcp.test.js, ui/__tests__/e2e/03-configure-cloud-aws.test.js, ui/__tests__/e2e/page-objects/configure/cloud/AWS/cluster-plans.js, ui/__tests__/e2e/page-objects/configure/cloud/AWS/cluster-policies.js, ui/__tests__/e2e/page-objects/configure/cloud/GCP/cluster-plans.js, ui/__tests__/e2e/page-objects/configure/cloud/GCP/cluster-policies.js, ui/__tests__/e2e/page-objects/configure/cloud/cluster-plans-base.js, ui/__tests__/e2e/page-objects/configure/cloud/cluster-policies-base.js, ui/lib/components/forms/AllocationsFormItem.js, ui/lib/components/policies/Policy.js, ui/lib/components/policies/PolicyForm.js, ui/lib/components/policies/PolicyList.js
Adds E2E tests for Cluster Policies (GKE and EKS), also a bit of housekeeping on the cluster plans tests and removing unnecessary docker engines from circle ci.
=> UI E2E Tests for Cluster Policies

ui/lib/prototype/components/teams/settings/EventNotificationForm.js, ui/lib/prototype/components/teams/settings/EventNotificationsTab.js, ui/lib/prototype/components/teams/settings/NotificationIntegrationsTab.js, ui/lib/prototype/utils/dummy-notification-data.js, ui/pages/prototype/index.js, ui/pages/prototype/teams/demo/costs/index.js, ui/pages/prototype/teams/demo/settings/notifications.js, ui/pages/prototype/teams/proto.js
**Team event notifications**
**Create event notification**
**Configure notification integrations**
=> [PROTOTYPE] Adding team notifications prototype

ui/__tests__/unit/lib/components/forms/NewTeamForm.test.js, ui/lib/components/forms/NewTeamForm.js, ui/lib/crd/Team.js, ui/lib/utils/model.js
* along with minor tweaks to the NewTeamForm component
=> Removing use of Team CRD template

test/e2e/check-suite-units.sh, test/e2e/integration/eks.bats, test/e2e/integration/secrets.bats
- fixing up the checks for the eksnodegroups
=> Fix EKS Tests

CHANGELOG.md, pkg/client/config/helper.go, pkg/client/config/types.go, pkg/cmd/kore/local/up.go, pkg/utils/home.go, pkg/utils/kubernetes/kubeconfig.go
Fixing the path for windows machines as we have hardcoded unix paths
Part of a hotfix
Removing the hard coded nature of the of paths
NA
NA
NA
Needs to be tested on a windows machine
`kore kubeconfig`
=> Kubeconfig

README.md
Resolves #1030 
Tag badge now links to the latest release rather than the image of the badge.
Please provide a list of important, but not strictly-related commits (e.g. you had to refactor a bigger component for a new feature).
=> docs(badge): tag badge url to latest release #1030

README.md
Resolves #1044 
This PR was done to demonstration open source contributions via a [live stream](https://youtu.be/OhDtycLDj2A) on my YouTube channel
License badge links to license file not the badge image
Before...
After...
=> docs(license): link added to license badge #1044

README.md
Resolves #
Please detail any major changes and provide the minimal documentation about how these work or do alter the current behaviour.
Anyone who reads this should understand the intention of this PR without reading the code.
Please provide a list of important, but not strictly-related commits (e.g. you had to refactor a bigger component for a new feature).
Please provide some screenshots of UI changes if relevant. This will help interested parties to quickly learn about some upcoming changes.
Please provide some CLI and/or manifest examples if relevant. This will help understand the changes and/or how to use new features.
Please provide detailed instructions about how to test this feature. …
=> Add walkthrough and service catalogue to readme

pkg/cmd/kore/get/get.go
🎶  Let's get physical, physical, I wanna get physical 🎶
I've added a `--raw` option to `kore get` (similarly to kubectl), so we can query the API directly. This simplifies debugging.
Also have you ever wanted to query the cloud metadata really easily? Now you can!
```
kore get --raw /metadata/k8s/aks/regions/uksouth/versions
[
"1.15.11",
"1.15.12",
"1.16.10",
"1.17.7"
]
```
```
kore get --raw "/whoami?foo=bar" --verbose
```
=> Add --raw option to 'kore get', so we can query the API directly

ui/lib/components/plans/UsePlanForm.js
Fixing issue with delayed loading of cluster settings
Resolves #1125 
* caused by a trigger happy condition on `componentDidUpdate` of the `UsePlanForm` component
* this would cause the cluster specific config to always be reset with the original plan config
* only noticeable once the cluster config has been changed from the original plan config
* the cluster specific config would be applied within 5 seconds of loading the settings tab when the main cluster page refreshed the data and pushed the cluster config as a prop into the component
* also fixed up a couple of other potentially fragile parts
I've thoroughly tested this fix however, to check the …
=> Fixing issue with delayed loading of cluster settings

ui/lib/components/teams/cluster/Cluster.js, ui/lib/prototype/components/teams/cluster/Cluster.js, ui/lib/utils/ui-helpers.js
The icon was missing, this fixes it and adds max width/height.
=> Show AKS cluster icon in the cluster list, constrain icon sizes correctly

.circleci/config.yml
Forgot to add the build-api to the nightly builds
Resolves Bug Fix
Adding the build-api job as a requirement
=> Nightly Builds Fix

ui/__tests__/unit/lib/utils/validation.test.js, ui/lib/components/credentials/AWSOrganizationForm.js, ui/lib/components/credentials/AWSOrganizationsList.js, ui/lib/utils/validation.js, ui/pages/configure/cloud/[...cloud].js
Provides the context and help for Kore users setting up aws account management.
Resolves #1122 
User interface in the Cloud, Settings, Amazon Web Services, Organization credentials
=> update aws account form with help warning and links

pkg/serviceproviders/awsservicebroker/factory.go
=> Set the IAM role component status to successful after creation for the aws service provider

pkg/utils/cloud/aws/accounts.go
We would try and provision new AWS accounts even when the old AWS account existed as we didn't cater for paginated organization get accounts api.
Resolves #1165 
- No new docs required
As described.
Check to see which accounts all ready exist in another environment but are past 20th in the list e.g:
```
aws organizations list-accounts | jq -r '.Accounts'
```
=> fix bug where all aws accounts were not listed with paginated results

ui/__tests__/unit/lib/kore-api/kore-api-resources.test.js, ui/lib/components/credentials/AWSOrganizationForm.js, ui/lib/components/credentials/AWSOrganizationsList.js, ui/lib/components/credentials/GCPOrganizationForm.js, ui/lib/components/setup/CloudSetup.js, ui/lib/components/setup/KoreManagedCloudAccounts.js, ui/lib/kore-api/kore-api-resources.js, ui/pages/setup/kore/cloud-access.js
As title
Resolves #1152
* the missing user prop was causing the form to break
Fixing an issue with the naming of AWS/GCP org allocations
* the name should be as typed, not the URI-friendly version
* creating/editing AWS/GCP organizations
=> Fixing issue with editing AWS organization

pkg/cmd/kore/login/login.go
Just cleaning up the statement to make it easier to read
Quick cleanup of the code to make it reader friendly
No logic changes, just aesthetic
=> Supported Methods Cleanup

.circleci/config.yml
=> Release Fix

doc/local-quick-start.md, pkg/cmd/kore/local/destroy.go
- fixing up the documentation links and the render of the destroy
=> Document Links

ui/pages/_app.js
Minor UI fix
Resolves #603 
Only set the `requestedPath` when it is defined.
=> Preventing requestedPath of undefined

doc/local-quick-start.md
Quick update of docs to add Helm3 which on attempted initialisation was needed.
Resolves #
None
N/A
N/A
Please provide detailed instructions about how to test this feature. This should include:
* testing requirements
* important test cases
N/A
If you've created any related stories which should be done in the future (but not as part of this PR), please record it here.
=> Add helm 3
